"""
Title pools for AlgoRot match results.
Categories: clutch (<=10% HP), blowout (>=25% HP), standard (everything else).
No ellipsis (...) or colons (:) in any title.
"""


def get_title_pools(f1_name, f2_name):
    """Return title pools dict keyed by category."""

    clutch = [
        f"The greatest 1 HP comeback in AlgoRot history",
        f"Someone actually survived on 1 HP in {f1_name} vs {f2_name}",
        f"Never count them out. INSANE Ending in {f1_name} vs {f2_name}",
        f"They thought it was over. Wait for it",
        f"The Ultimate Underdog Story in {f1_name} vs {f2_name}",
        f"A literal miracle in the final seconds of {f1_name} vs {f2_name}",
        f"Greatest Plot Twist. Someone refuses to die",
        f"99 percent of people thought this was over. Then they woke up",
        f"How did they survive that? (1 HP Comeback in {f1_name} vs {f2_name})",
        f"A massive lead just got CHOKED in {f1_name} vs {f2_name}",
        f"The exact moment the tables turned in {f1_name} vs {f2_name}",
        f"The craziest buzzer-beater win yet in AlgoRot",
        f"From the brink of defeat. A legendary clutch in {f1_name} vs {f2_name}",
        f"Do not swipe away. This comeback is pure cinema",
        f"{f1_name} vs {f2_name} goes down to the wire",
        f"This should have been over in 10 seconds. It was not",
        f"The comeback nobody saw coming in {f1_name} vs {f2_name}",
        f"1 HP left and they STILL found a way to win",
        f"The most dramatic survival moment in AlgoRot history",
        f"Bro really said no to dying. {f1_name} vs {f2_name}",
        f"This is the most stressful 30 seconds in AlgoRot",
        f"They had one HP. ONE. And they still won",
        f"The crowd would have gone absolutely insane for this one",
        f"The underdog win that broke every prediction",
        f"When the algorithm refuses to give up. {f1_name} vs {f2_name}",
        f"You will not believe who survives in {f1_name} vs {f2_name}",
        f"Down bad and STILL clutching up in {f1_name} vs {f2_name}",
        f"This HP was so low it should have been illegal",
        f"The last possible moment comeback in {f1_name} vs {f2_name}",
        f"Thought it was over? Think again. {f1_name} vs {f2_name}",
        f"The moment {f1_name} vs {f2_name} became a horror movie",
        f"Ghost HP energy. {f1_name} vs {f2_name} defies all logic",
        f"The last gasp win that nobody predicted in AlgoRot",
        f"They were invisible on the HP bar and STILL pulled through",
        f"Nothing should have saved them. Something did",
        f"A survival story that belongs in the AlgoRot Hall of Fame",
        f"The fight that proves one HP is enough",
        f"How is this even possible? {f1_name} vs {f2_name} shocks everyone",
        f"A victory so improbable the simulation almost broke",
        f"They played dead and then absolutely did not die",
        f"The HP bar said no chance. The fighter said watch me",
        f"One pixel of health and all the heart in the world",
        f"The math did not add up. They won anyway. {f1_name} vs {f2_name}",
        f"This AlgoRot match gave me actual anxiety",
        f"The most nail-biting finish in {f1_name} vs {f2_name} yet",
        f"When survival instinct overrides everything else in AlgoRot",
        f"The fighter that physics forgot to kill in {f1_name} vs {f2_name}",
        f"Running on pure chaos and zero HP in {f1_name} vs {f2_name}",
        f"The most cinematic last stand in AlgoRot history",
        f"They literally should not have made it out of this one",
        f"Snatching victory from the jaws of total destruction",
        f"The final second save that rewrote the whole story",
        f"This HP was basically decorative. They won anyway",
        f"A comeback so good it felt scripted in {f1_name} vs {f2_name}",
        f"This is what happens when you refuse to tap out",
        f"The AlgoRot fighter with absolutely zero chill about losing",
        f"Surviving on fumes and somehow winning in {f1_name} vs {f2_name}",
        f"One hit away from defeat and they found two hits of their own",
        f"The moment {f1_name} vs {f2_name} turned into a comeback story",
        f"Running on luck fumes and nothing else in this AlgoRot match",
        f"The win that rewired my brain a little bit",
        f"Technically dead but emotionally very much alive",
        f"How many times can one fighter cheat death? AlgoRot answers",
        f"The HP bar was a lie and {f1_name} vs {f2_name} proved it",
        f"Refusing to go down no matter what in {f1_name} vs {f2_name}",
        f"The last breath win that belongs in AlgoRot lore",
        f"Nobody picks the underdog. The underdog does not care",
        f"Surviving when the odds said absolutely not in AlgoRot",
        f"An HP that small should be a death sentence. It was not",
        f"The comeback arc in {f1_name} vs {f2_name} is genuinely unreal",
        f"Who programmed this fighter to never give up?",
        f"Against all probability this is what happened in {f1_name} vs {f2_name}",
        f"The most heart-racing AlgoRot finish of the season",
        f"A win built entirely out of stubbornness and physics",
        f"The ghost health bar victory in {f1_name} vs {f2_name}",
        f"One last swing and somehow it landed in AlgoRot",
        f"The entire vibe of this fight changed in the last second",
        f"Clinging to life and winning anyway in {f1_name} vs {f2_name}",
        f"The simulation said it was over. The fighter disagreed",
        f"You physically cannot predict the ending of {f1_name} vs {f2_name}",
        f"The luckiest alive fighter in all of AlgoRot",
        f"This match had ZERO business going the way it did",
        f"From deletion territory to outright winning in {f1_name} vs {f2_name}",
        f"The most emotionally devastating comeback in AlgoRot",
        f"AlgoRot does it again. You will not see this ending coming",
        f"Barely a health bar left but all the fight in the world",
        f"The comeback that nobody in AlgoRot history can top",
        f"Surviving by a miracle and capitalizing on it in {f1_name} vs {f2_name}",
        f"Technically on borrowed time. Absolutely did not show it",
        f"The most insane survival in AlgoRot this year",
        f"They had nothing left. They still had enough",
        f"The ending of {f1_name} vs {f2_name} will haunt me",
        f"Fighting on fumes against a full tank in AlgoRot",
        f"The 1 HP win that set the AlgoRot community on fire",
        f"This should have ended five hits earlier. It did not",
        f"AlgoRot physics just handed someone the most dramatic win ever",
        f"Living on the edge and THRIVING in {f1_name} vs {f2_name}",
        f"Nobody expected this ending in {f1_name} vs {f2_name}. Nobody",
        f"The last laugh goes to the fighter everyone counted out",
    ]

    blowout = [
        f"ABSOLUTE DOMINATION in {f1_name} vs {f2_name}",
        f"Is one of these colors broken in AlgoRot?",
        f"FLAWLESS VICTORY. Someone gets absolutely destroyed",
        f"Nobody can stop them. Just watch",
        f"They did not stand a chance",
        f"The most one-sided battle in AlgoRot history",
        f"Pure Destruction in {f1_name} vs {f2_name}",
        f"Someone just proved they are the final boss of AlgoRot",
        f"A masterclass in physics and total domination",
        f"Someone got absolutely vaporized in {f1_name} vs {f2_name}",
        f"Speedrun energy. Finished with ZERO MERCY",
        f"Are they cheating? (Flawless Win in {f1_name} vs {f2_name})",
        f"Casually wiping the floor with their opponent in AlgoRot",
        f"Total annihilation. Zero damage taken",
        f"They need to be deleted after what just happened in AlgoRot",
        f"This was not a fight. This was an execution",
        f"The most lopsided physics battle AlgoRot has ever produced",
        f"One fighter showed up. The other just got erased",
        f"Is this even fair? {f1_name} vs {f2_name} is brutal",
        f"Maximum efficiency. Minimum mercy in AlgoRot",
        f"They took zero damage and gave everything in {f1_name} vs {f2_name}",
        f"A complete shutdown performance in AlgoRot",
        f"This was a demolition dressed up as a battle",
        f"The most dominant AlgoRot win I have ever seen",
        f"Did someone forget to give the other fighter a sword?",
        f"A performance so clean it feels illegal in {f1_name} vs {f2_name}",
        f"From start to finish there was only one fighter here",
        f"The simulation had no answer for this level of dominance",
        f"This AlgoRot run is what peak performance looks like",
        f"Untouchable. Unstoppable. Unreal performance in {f1_name} vs {f2_name}",
        f"The most complete destruction in AlgoRot history",
        f"They treated this fight like a warmup",
        f"Not a single scratch. Just pure AlgoRot supremacy",
        f"The opponent barely existed in this one",
        f"Absolute unit energy in {f1_name} vs {f2_name}",
        f"This was not competitive. This was a showcase",
        f"Zero HP taken. Zero hesitation. Total victory in AlgoRot",
        f"The kind of win that makes you wonder if the code is rigged",
        f"A physics-powered freight train with no brakes in {f1_name} vs {f2_name}",
        f"They did not just win. They sent a message in AlgoRot",
        f"The most effortless flawless run in {f1_name} vs {f2_name}",
        f"Watching this domination felt genuinely unfair",
        f"If AlgoRot had a final boss it would look exactly like this",
        f"The other fighter showed up but was never really in it",
        f"Peak AlgoRot performance and it was not even close",
        f"Absolute zero competition in {f1_name} vs {f2_name}",
        f"They dismantled the opponent piece by piece in AlgoRot",
        f"This fighter did not leave anything on the table",
        f"The cleanest win in recent AlgoRot memory",
        f"No drama needed when you are this dominant",
        f"A shutout performance for the AlgoRot record books",
        f"The most one-way traffic in the history of {f1_name} vs {f2_name}",
        f"They made it look painfully easy in AlgoRot",
        f"Is this physics or is this art? {f1_name} vs {f2_name}",
        f"Full health at the end. Did not even break a sweat",
        f"The opponent had no answer at any point in {f1_name} vs {f2_name}",
        f"The algorithm cooked something truly terrifying today in AlgoRot",
        f"Dominant from the very first collision in {f1_name} vs {f2_name}",
        f"This win was so clean it barely made a sound",
        f"An absolutely clinical performance in {f1_name} vs {f2_name}",
        f"The gap between these two fighters is honestly shocking",
        f"Never in danger. Always in control in {f1_name} vs {f2_name}",
        f"The most convincing win the AlgoRot simulation has ever generated",
        f"Completely outclassed in every single dimension in AlgoRot",
        f"This fighter did not take damage. They gave a lesson",
        f"The performance of a lifetime by AlgoRot standards",
        f"Imagine getting this destroyed with full health still showing",
        f"A total obliteration that the simulation is still processing",
        f"Nobody who watched this doubted who was going to win",
        f"The other fighter was more of a prop than a participant",
        f"Surgical precision and zero sympathy in {f1_name} vs {f2_name}",
        f"They ran through the opponent like they were not even there",
        f"A performance so dominant it almost feels scripted in AlgoRot",
        f"The most terrifying thing in AlgoRot is this flawless run",
        f"You can tell from the very first second who is winning this",
        f"A FLAWLESS W that needs to be studied in {f1_name} vs {f2_name}",
        f"Why does this keep happening to {f2_name}? AlgoRot has questions",
        f"This fighter was always going to win and the algorithm knew it",
        f"One fighter brought a sword. The other brought thoughts and prayers",
        f"They took the game personally and the opponent paid for it",
        f"The most embarrassing HP differential in {f1_name} vs {f2_name} history",
        f"A win so large it barely fits on the HP bar",
        f"Completely sealed from the opening collision in AlgoRot",
        f"The other fighter was simply outmatched from the start",
        f"They ran the algorithm better than the algorithm expected",
        f"Total health remaining after a FLAWLESS annihilation in AlgoRot",
        f"The physics engine bowed down during this {f1_name} vs {f2_name} run",
        f"Poured everything out and never took a drop back in AlgoRot",
        f"What a thing to witness. Pure AlgoRot supremacy",
        f"The kind of performance that makes other fighters delete themselves",
        f"Historically dominant. This AlgoRot match is required viewing",
        f"Zero contest. Zero drama. All dominance in {f1_name} vs {f2_name}",
        f"This fighter ran the table and never looked back in AlgoRot",
        f"The perfect AlgoRot run that might never be repeated",
        f"This is what happens when the algorithm absolutely cooks",
        f"A W so clean the simulation had to double check it was real",
        f"They absorbed nothing and delivered everything in {f1_name} vs {f2_name}",
        f"The most dominant AlgoRot fighter we have seen all season",
        f"No sweat. No damage. Just results in {f1_name} vs {f2_name}",
    ]

    standard = [
        f"{f1_name} vs {f2_name} ends in SHOCKING Sudden Death",
        f"The physics in this {f1_name} vs {f2_name} match went CRAZY",
        f"10 Parries Later. {f1_name} vs {f2_name} goes Nuclear",
        f"This {f1_name} vs {f2_name} Sudden Death will give you chills",
        f"NO WAY. The {f1_name} vs {f2_name} Match Was Too Close",
        f"Wait until the end of this {f1_name} vs {f2_name} fight",
        f"You won not believe how {f1_name} vs {f2_name} ends",
        f"Are we dreaming? {f1_name} vs {f2_name} goes off the rails",
        f"This collision between {f1_name} and {f2_name} broke the engine",
        f"The most intense rivalry yet in {f1_name} vs {f2_name}",
        f"Pure satisfying chaos in {f1_name} vs {f2_name} Sudden Death",
        f"My brain melted watching {f1_name} vs {f2_name}",
        f"Who are you rooting for? {f1_name} vs {f2_name} Epic Ending",
        f"Gravity stopped working in this {f1_name} vs {f2_name} clash",
        f"The exact moment {f1_name} vs {f2_name} turned into a movie",
        f"This match had absolutely no right to be this entertaining",
        f"The most unpredictable AlgoRot battle of the week",
        f"Neither side could pull away in this wild {f1_name} vs {f2_name} brawl",
        f"The turning point in {f1_name} vs {f2_name} will blow your mind",
        f"A fight so chaotic the simulation had to catch its breath",
        f"Every swing mattered in this insane {f1_name} vs {f2_name} matchup",
        f"AlgoRot served up something special with {f1_name} vs {f2_name}",
        f"The most evenly matched AlgoRot battle in recent memory",
        f"Back and forth chaos all the way to the final blow",
        f"The AlgoRot algorithm absolutely went unhinged in {f1_name} vs {f2_name}",
        f"Two equals going to war. Only one survives in AlgoRot",
        f"This fight had no business being this good",
        f"Completely unpredictable from first hit to last in {f1_name} vs {f2_name}",
        f"The most watched AlgoRot rematch about to happen after this",
        f"The physics engine went full drama mode in {f1_name} vs {f2_name}",
        f"An absolute banger of a match from start to finish",
        f"The moment {f1_name} vs {f2_name} became legendary in AlgoRot",
        f"AlgoRot just generated something that cannot be unseen",
        f"Close. Intense. Chaotic. {f1_name} vs {f2_name} had everything",
        f"The match that made me forget to breathe in {f1_name} vs {f2_name}",
        f"The simulation decided to go full cinematic in this one",
        f"Not a single dull moment in this {f1_name} vs {f2_name} battle",
        f"The most satisfying ending AlgoRot has produced this week",
        f"Nobody could predict this result in {f1_name} vs {f2_name}",
        f"When the algorithm decides to get dramatic in AlgoRot",
        f"A razor-thin margin decided this wild {f1_name} vs {f2_name} fight",
        f"The cleanest AlgoRot chaotic brawl you will see today",
        f"This kind of finish is exactly why AlgoRot has fans",
        f"AlgoRot physics went completely sideways in {f1_name} vs {f2_name}",
        f"Two fighters. One winner. Zero predictability in AlgoRot",
        f"The most dramatic HP race in {f1_name} vs {f2_name} history",
        f"An AlgoRot battle that kept swinging right until the end",
        f"The collision that changed everything in {f1_name} vs {f2_name}",
        f"This is what peak algorithmic combat looks like",
        f"Fighting until nothing is left in {f1_name} vs {f2_name}",
        f"Absolutely zero chill from either fighter in this AlgoRot match",
        f"The most watched fight on the channel is about to be this one",
        f"Total warfare from the first frame in {f1_name} vs {f2_name}",
        f"An AlgoRot matchup that deserves to be studied",
        f"Both fighters showed up prepared to destroy in {f1_name} vs {f2_name}",
        f"The match that defined the entire {f1_name} vs {f2_name} rivalry",
        f"AlgoRot finally gave us the {f1_name} vs {f2_name} match we deserved",
        f"The fight that got away from both sides in AlgoRot",
        f"When the damage numbers get big things get real fast in AlgoRot",
        f"The greatest battle in the {f1_name} vs {f2_name} series so far",
        f"This AlgoRot fight has more plot twists than a short film",
        f"Completely even right up until the moment it was not",
        f"The final exchange in {f1_name} vs {f2_name} is everything",
        f"Mayhem physics and a ridiculous ending in {f1_name} vs {f2_name}",
        f"This is exactly why I watch AlgoRot every single day",
        f"Two unstoppable forces. One unforgettable result in AlgoRot",
        f"The battle that shook the AlgoRot leaderboard in {f1_name} vs {f2_name}",
        f"Sheer aggression from both sides right until the final frame",
        f"Tied on chaos. Decided by physics in {f1_name} vs {f2_name}",
        f"The match that AlgoRot was literally built to generate",
        f"A rivalry match so good it needs a sequel in AlgoRot",
        f"When the HP bars get this close the crowd loses it",
        f"This fight aged five years in thirty seconds in AlgoRot",
        f"The intensity of {f1_name} vs {f2_name} is almost too much",
        f"If you only watch one AlgoRot fight today make it this one",
        f"This outcome in {f1_name} vs {f2_name} made absolutely no sense and yet",
        f"The simulation generated something extraordinary in this match",
        f"When two fighters are this close sparks literally fly in AlgoRot",
        f"The most evenly balanced AlgoRot fight of the entire season",
        f"Neither side blinked in this {f1_name} vs {f2_name} showdown",
        f"The moment this AlgoRot match stopped being normal",
        f"A genuine classic in the making from {f1_name} vs {f2_name}",
        f"When AlgoRot says no mercy it absolutely means it",
        f"This battle had energy from the very first sword swing",
        f"The ending of {f1_name} vs {f2_name} will be talked about for days",
        f"AlgoRot has never generated a closer fight than this one",
        f"The most chaotically balanced battle in the entire series",
        f"A fight where every single decision mattered in {f1_name} vs {f2_name}",
        f"Neither fighter wanted to be the one who lost this one",
        f"The algorithm completely lost the plot in {f1_name} vs {f2_name}",
        f"Head-to-head and completely unpredictable in AlgoRot",
        f"The most dramatic trading sequence in {f1_name} vs {f2_name} history",
        f"This AlgoRot match ended in a way nobody in the comments predicted",
        f"A genuinely wild ride from first hit to last breath in AlgoRot",
        f"AlgoRot peaked today and it peaked during {f1_name} vs {f2_name}",
        f"The simulation generated drama and then kept going in AlgoRot",
        f"Equal damage. Unequal endings. The beauty of {f1_name} vs {f2_name}",
        f"The most competitive fight the algorithm has ever produced",
        f"Both fighters threw everything and only one thing remained in AlgoRot",
    ]

    return {
        "clutch": clutch,
        "blowout": blowout,
        "standard": standard,
    }