"""
Title generation system for AlgoRot match results.

This module provides curated pools of viral-focused titles categorized by the 
intensity and outcome of a match. The titles are designed for short-form 
content (TikTok/YT Shorts), prioritizing high-energy hooks and engagement.

Category Definitions:
    ghost:    Exactly 0% HP left (phantom victory, rarest outcome).
    clutch:   1-10% HP left (nail-biting survival).
    standard: 11-39% HP left (competitive, back-and-forth).
    blowout:  40-59% HP left (dominant win).
    stomp:    60%+ HP left (near-perfect, untouchable run).

Note: Titles avoid punctuation like ellipses (...) or colons (:) to maintain 
clean aesthetics in UI overlays and file names.
"""


def get_title_pools(f1_name: str, f2_name: str) -> dict:
    """Returns a dictionary of title pools populated with fighter names.

    Args:
        f1_name: Name of the first fighter (e.g., "Blue").
        f2_name: Name of the second fighter (e.g., "Red").

    Returns:
        dict: Title lists keyed by category ('ghost', 'clutch', etc.).
    """

    ghost = [
        f"The 0 HP win that should not exist in {f1_name} vs {f2_name}",
        f"Technically on zero and still standing in AlgoRot",
        f"Physics said 0. The fighter said otherwise",
        f"A ghost win. Zero HP and somehow still here",
        f"The simulation registered zero and kept going anyway",
        f"Zero HP. Full victory. AlgoRot defies its own rules",
        f"They flatlined and still crossed the finish line",
        f"This is not possible but it just happened in {f1_name} vs {f2_name}",
        f"The most impossible win in AlgoRot runs on HP it does not have",
        f"0 HP on the bar. W in the record. The simulation is broken",
        f"The ghost run that rewrote the AlgoRot rulebook",
        f"Running on negative HP energy in {f1_name} vs {f2_name}",
        f"A victory built on absolutely nothing but will",
        f"The HP bar hit zero and the fighter kept going",
        f"There should be a law against surviving on this in AlgoRot",
        f"They had no HP. The scoreboard did not agree with that",
        f"Zero is a number. It is also apparently enough to win",
        f"The AlgoRot match that made the developers question everything",
        f"A 0 HP victory so rare it might never happen again",
        f"The sim said dead. The algorithm said let them cook",
        f"Surviving on nothing and winning on everything in AlgoRot",
        f"The fighter that the HP bar forgot to kill in {f1_name} vs {f2_name}",
        f"No HP left. No problem. No explanation in AlgoRot",
        f"Zero on the clock and zero on the bar. One of them walks out anyway",
        f"This is either a miracle or a bug and it does not matter which",
        f"The last tick of HP and somehow it was enough in {f1_name} vs {f2_name}",
        f"A phantom victory that the leaderboard will never forget",
        f"They should have been deleted. They were not",
        f"Running on vibes and 0 HP in {f1_name} vs {f2_name}",
        f"The fight was over. Someone forgot to tell the fighter",
        f"Zero HP. Not zero will. AlgoRot proves math is optional",
        f"This is the rarest outcome in AlgoRot history",
        f"The most technically dead winner in {f1_name} vs {f2_name}",
        f"A win that required exactly zero HP and infinite spirit",
        f"The HP bar begged them to stop. They refused",
        f"Existing past the point of logic in {f1_name} vs {f2_name}",
        f"The zero HP special. A legendary rarity in AlgoRot",
        f"This fighter borrowed HP from the next dimension",
        f"A scoreline that should not be legal in AlgoRot",
        f"They were at zero. They still won. AlgoRot has no rules",
        f"The most statistically improbable win in {f1_name} vs {f2_name}",
        f"The HP display showed nothing. The W display showed everything",
        f"Fighting past the HP limit in {f1_name} vs {f2_name}",
        f"The ghost walk victory that AlgoRot fans will talk about forever",
        f"Technically eliminated. Actually victorious. AlgoRot does it again",
        f"When the simulation refuses to let you lose in {f1_name} vs {f2_name}",
        f"A 0 HP performance so absurd it deserves a trophy",
        f"Dying on paper. Winning on the scoreboard. AlgoRot math",
        f"The least amount of HP ever used to win in AlgoRot",
        f"A finish line crossed with nothing left in the tank",
        f"They had 0 and made it count in {f1_name} vs {f2_name}",
        f"The shadow victory. No HP. All heart in AlgoRot",
        f"This is what winning looks like when physics stops working",
        f"An AlgoRot win powered entirely by unexplained forces",
        f"The simulation glitched. The victory was real in {f1_name} vs {f2_name}",
        f"The most technically wrong winner in AlgoRot and yet",
        f"A champion that the HP bar already gave up on",
        f"0 percent HP. 100 percent victory. AlgoRot refuses logic",
        f"The void cannot stop this fighter in {f1_name} vs {f2_name}",
        f"Running on borrowed time and crossing the finish line anyway",
        f"This win should be studied in every physics class in AlgoRot",
        f"The moment the simulation said wait a second in {f1_name} vs {f2_name}",
        f"Existing at 0 HP and still having the audacity to win",
        f"A victory forged from pure stubbornness in AlgoRot",
        f"The most haunting win condition in {f1_name} vs {f2_name}",
        f"There is no HP left. There is only the win",
        f"AlgoRot finally produced the impossible 0 HP win",
        f"This fighter did not get the memo about having zero HP",
        f"The luckiest bracket in AlgoRot goes to {f1_name} vs {f2_name}",
        f"Hollow and victorious in {f1_name} vs {f2_name}",
        f"The deadliest 0 HP fighter AlgoRot has ever generated",
        f"A result that broke the leaderboard and the laws of physics",
        f"You cannot kill what refuses to check its own HP bar",
        f"This match ended at zero and started a legend in AlgoRot",
        f"The most unexpected survivor in {f1_name} vs {f2_name} history",
        f"Zero. That is the HP. That is also apparently enough",
        f"A ghost of a win in {f1_name} vs {f2_name} that will never fade",
        f"The 0 HP special that AlgoRot saved for the right moment",
        f"The emptiest HP bar. The fullest victory in AlgoRot",
        f"Summoning a win from literally nothing in {f1_name} vs {f2_name}",
        f"The match that proved HP is just a suggestion in AlgoRot",
        f"A round that ended at zero and launched a legend",
        f"Nobody with 0 HP has ever won like this in AlgoRot",
        f"Flatline energy. Championship result in {f1_name} vs {f2_name}",
        f"The zero percent survival rate just became one hundred",
        f"A hollow fighter with a very full record in AlgoRot",
        f"The simulation ran out of HP before it ran out of fight",
        f"Crossing the finish line with the tanks completely empty",
        f"This is AlgoRot at its most unhinged and we love it",
        f"The rarest 0 HP win in the entire AlgoRot archive",
        f"An outcome so unlikely the simulation had to run it twice",
        f"A title earned with absolutely zero HP to spare in AlgoRot",
        f"The fight is over. Nobody told the winner in {f1_name} vs {f2_name}",
        f"Winning from the grave in {f1_name} vs {f2_name}",
        f"No health. No problem. A legendary moment in AlgoRot",
        f"The 0 HP win that turns a round into a story",
        f"This victory should have required more HP. It did not",
        f"At exactly zero and still the last one standing in AlgoRot",
        f"The most ghost energy win in {f1_name} vs {f2_name} all season",
        f"A fighter technically dead and practically unstoppable in AlgoRot",
    ]

    clutch = [
        f"The greatest 1 HP comeback in AlgoRot history",
        f"Someone actually survived on 1 HP in {f1_name} vs {f2_name}",
        f"Never count them out. INSANE Ending in {f1_name} vs {f2_name}",
        f"They thought it was over. Wait for it",
        f"The Ultimate Underdog Story in {f1_name} vs {f2_name}",
        f"A literal miracle in the final seconds of {f1_name} vs {f2_name}",
        f"Greatest Plot Twist. Someone refuses to die",
        f"99 percent of people thought this was over. Then they woke up",
        f"How did they survive that? (1 HP Comeback in {f1_name} vs {f2_name})",
        f"A massive lead just got CHOKED in {f1_name} vs {f2_name}",
        f"The exact moment the tables turned in {f1_name} vs {f2_name}",
        f"The craziest buzzer-beater win yet in AlgoRot",
        f"From the brink of defeat. A legendary clutch in {f1_name} vs {f2_name}",
        f"Do not swipe away. This comeback is pure cinema",
        f"{f1_name} vs {f2_name} goes down to the wire",
        f"This should have been over in 10 seconds. It was not",
        f"The comeback nobody saw coming in {f1_name} vs {f2_name}",
        f"1 HP left and they STILL found a way to win",
        f"The most dramatic survival moment in AlgoRot history",
        f"Bro really said no to dying. {f1_name} vs {f2_name}",
        f"This is the most stressful 30 seconds in AlgoRot",
        f"They had one HP. ONE. And they still won",
        f"The crowd would have gone absolutely insane for this one",
        f"The underdog win that broke every prediction",
        f"When the algorithm refuses to give up. {f1_name} vs {f2_name}",
        f"You will not believe who survives in {f1_name} vs {f2_name}",
        f"Down bad and STILL clutching up in {f1_name} vs {f2_name}",
        f"This HP was so low it should have been illegal",
        f"The last possible moment comeback in {f1_name} vs {f2_name}",
        f"Thought it was over? Think again. {f1_name} vs {f2_name}",
        f"The moment {f1_name} vs {f2_name} became a horror movie",
        f"Ghost HP energy. {f1_name} vs {f2_name} defies all logic",
        f"The last gasp win that nobody predicted in AlgoRot",
        f"They were invisible on the HP bar and STILL pulled through",
        f"Nothing should have saved them. Something did",
        f"A survival story that belongs in the AlgoRot Hall of Fame",
        f"The fight that proves one HP is enough",
        f"How is this even possible? {f1_name} vs {f2_name} shocks everyone",
        f"A victory so improbable the simulation almost broke",
        f"They played dead and then absolutely did not die",
        f"The HP bar said no chance. The fighter said watch me",
        f"One pixel of health and all the heart in the world",
        f"The math did not add up. They won anyway. {f1_name} vs {f2_name}",
        f"This AlgoRot match gave me actual anxiety",
        f"The most nail-biting finish in {f1_name} vs {f2_name} yet",
        f"When survival instinct overrides everything else in AlgoRot",
        f"The fighter that physics forgot to kill in {f1_name} vs {f2_name}",
        f"Running on pure chaos and zero HP in {f1_name} vs {f2_name}",
        f"The most cinematic last stand in AlgoRot history",
        f"They literally should not have made it out of this one",
        f"Snatching victory from the jaws of total destruction",
        f"The final second save that rewrote the whole story",
        f"This HP was basically decorative. They won anyway",
        f"A comeback so good it felt scripted in {f1_name} vs {f2_name}",
        f"This is what happens when you refuse to tap out",
        f"The AlgoRot fighter with absolutely zero chill about losing",
        f"Surviving on fumes and somehow winning in {f1_name} vs {f2_name}",
        f"One hit away from defeat and they found two hits of their own",
        f"The moment {f1_name} vs {f2_name} turned into a comeback story",
        f"Running on luck fumes and nothing else in this AlgoRot match",
        f"The win that rewired my brain a little bit",
        f"Technically dead but emotionally very much alive",
        f"How many times can one fighter cheat death? AlgoRot answers",
        f"The HP bar was a lie and {f1_name} vs {f2_name} proved it",
        f"Refusing to go down no matter what in {f1_name} vs {f2_name}",
        f"The last breath win that belongs in AlgoRot lore",
        f"Nobody picks the underdog. The underdog does not care",
        f"Surviving when the odds said absolutely not in AlgoRot",
        f"An HP that small should be a death sentence. It was not",
        f"The comeback arc in {f1_name} vs {f2_name} is genuinely unreal",
        f"Who programmed this fighter to never give up?",
        f"Against all probability this is what happened in {f1_name} vs {f2_name}",
        f"The most heart-racing AlgoRot finish of the season",
        f"A win built entirely out of stubbornness and physics",
        f"The ghost health bar victory in {f1_name} vs {f2_name}",
        f"One last swing and somehow it landed in AlgoRot",
        f"The entire vibe of this fight changed in the last second",
        f"Clinging to life and winning anyway in {f1_name} vs {f2_name}",
        f"The simulation said it was over. The fighter disagreed",
        f"You physically cannot predict the ending of {f1_name} vs {f2_name}",
        f"The luckiest alive fighter in all of AlgoRot",
        f"This match had ZERO business going the way it did",
        f"From deletion territory to outright winning in {f1_name} vs {f2_name}",
        f"The most emotionally devastating comeback in AlgoRot",
        f"AlgoRot does it again. You will not see this ending coming",
        f"Barely a health bar left but all the fight in the world",
        f"The comeback that nobody in AlgoRot history can top",
        f"Surviving by a miracle and capitalizing on it in {f1_name} vs {f2_name}",
        f"Technically on borrowed time. Absolutely did not show it",
        f"The most insane survival in AlgoRot this year",
        f"They had nothing left. They still had enough",
        f"The ending of {f1_name} vs {f2_name} will haunt me",
        f"Fighting on fumes against a full tank in AlgoRot",
        f"The 1 HP win that set the AlgoRot community on fire",
        f"This should have ended five hits earlier. It did not",
        f"AlgoRot physics just handed someone the most dramatic win ever",
        f"Living on the edge and THRIVING in {f1_name} vs {f2_name}",
        f"Nobody expected this ending in {f1_name} vs {f2_name}. Nobody",
        f"The last laugh goes to the fighter everyone counted out",
        f"A comeback so improbable the simulation flagged it as an error",
    ]

    blowout = [
        f"ABSOLUTE DOMINATION in {f1_name} vs {f2_name}",
        f"Is one of these fighters broken in AlgoRot?",
        f"FLAWLESS VICTORY. Someone gets absolutely destroyed",
        f"Nobody can stop them. Just watch",
        f"They did not stand a chance",
        f"The most one-sided battle in AlgoRot history",
        f"Pure Destruction in {f1_name} vs {f2_name}",
        f"Someone just proved they are the final boss of AlgoRot",
        f"A masterclass in physics and total domination",
        f"Someone got absolutely vaporized in {f1_name} vs {f2_name}",
        f"Speedrun energy. Finished with ZERO MERCY",
        f"Are they cheating? (Flawless Win in {f1_name} vs {f2_name})",
        f"Casually wiping the floor with their opponent in AlgoRot",
        f"Total annihilation. Zero damage taken",
        f"They need to be deleted after what just happened in AlgoRot",
        f"This was not a fight. This was an execution",
        f"The most lopsided physics battle AlgoRot has ever produced",
        f"One fighter showed up. The other just got erased",
        f"Is this even fair? {f1_name} vs {f2_name} is brutal",
        f"Maximum efficiency. Minimum mercy in AlgoRot",
        f"They took zero damage and gave everything in {f1_name} vs {f2_name}",
        f"A complete shutdown performance in AlgoRot",
        f"This was a demolition dressed up as a battle",
        f"The most dominant AlgoRot win I have ever seen",
        f"Did someone forget to give the other fighter a weapon?",
        f"A performance so clean it feels illegal in {f1_name} vs {f2_name}",
        f"From start to finish there was only one fighter here",
        f"The simulation had no answer for this level of dominance",
        f"This AlgoRot run is what peak performance looks like",
        f"Untouchable. Unstoppable. Unreal performance in {f1_name} vs {f2_name}",
        f"The most complete destruction in AlgoRot history",
        f"They treated this fight like a warmup",
        f"Not a single scratch. Just pure AlgoRot supremacy",
        f"The opponent barely existed in this one",
        f"Absolute unit energy in {f1_name} vs {f2_name}",
        f"This was not competitive. This was a showcase",
        f"Zero HP taken. Zero hesitation. Total victory in AlgoRot",
        f"The kind of win that makes you wonder if the code is rigged",
        f"A physics-powered freight train with no brakes in {f1_name} vs {f2_name}",
        f"They did not just win. They sent a message in AlgoRot",
        f"The most effortless flawless run in {f1_name} vs {f2_name}",
        f"Watching this domination felt genuinely unfair",
        f"If AlgoRot had a final boss it would look exactly like this",
        f"The other fighter showed up but was never really in it",
        f"Peak AlgoRot performance and it was not even close",
        f"Absolute zero competition in {f1_name} vs {f2_name}",
        f"They dismantled the opponent piece by piece in AlgoRot",
        f"This fighter did not leave anything on the table",
        f"The cleanest win in recent AlgoRot memory",
        f"No drama needed when you are this dominant",
        f"A shutout performance for the AlgoRot record books",
        f"The most one-way traffic in the history of {f1_name} vs {f2_name}",
        f"They made it look painfully easy in AlgoRot",
        f"Is this physics or is this art? {f1_name} vs {f2_name}",
        f"Full health at the end. Did not even break a sweat",
        f"The opponent had no answer at any point in {f1_name} vs {f2_name}",
        f"The algorithm cooked something truly terrifying today in AlgoRot",
        f"Dominant from the very first collision in {f1_name} vs {f2_name}",
        f"This win was so clean it barely made a sound",
        f"An absolutely clinical performance in {f1_name} vs {f2_name}",
        f"The gap between these two fighters is honestly shocking",
        f"Never in danger. Always in control in {f1_name} vs {f2_name}",
        f"The most convincing win the AlgoRot simulation has ever generated",
        f"Completely outclassed in every single dimension in AlgoRot",
        f"This fighter did not take damage. They gave a lesson",
        f"The performance of a lifetime by AlgoRot standards",
        f"Imagine getting this destroyed with full health still showing",
        f"A total obliteration that the simulation is still processing",
        f"Nobody who watched this doubted who was going to win",
        f"The other fighter was more of a prop than a participant",
        f"Surgical precision and zero sympathy in {f1_name} vs {f2_name}",
        f"They ran through the opponent like they were not even there",
        f"A performance so dominant it almost feels scripted in AlgoRot",
        f"The most terrifying thing in AlgoRot is this flawless run",
        f"You can tell from the very first second who is winning this",
        f"A FLAWLESS W that needs to be studied in {f1_name} vs {f2_name}",
        f"Why does this keep happening in AlgoRot? Completely one-sided",
        f"This fighter was always going to win and the algorithm knew it",
        f"One fighter brought everything. The other brought nothing",
        f"They took the game personally and the opponent paid for it",
        f"The most embarrassing HP differential in {f1_name} vs {f2_name} history",
        f"A win so large it barely fits on the HP bar",
        f"Completely sealed from the opening collision in AlgoRot",
        f"The other fighter was simply outmatched from the start",
        f"They ran the algorithm better than the algorithm expected",
        f"Total health remaining after a FLAWLESS annihilation in AlgoRot",
        f"The physics engine bowed down during this {f1_name} vs {f2_name} run",
        f"Poured everything out and never took a drop back in AlgoRot",
        f"What a thing to witness. Pure AlgoRot supremacy",
        f"The kind of performance that makes other fighters delete themselves",
        f"Historically dominant. This AlgoRot match is required viewing",
        f"Zero contest. Zero drama. All dominance in {f1_name} vs {f2_name}",
        f"This fighter ran the table and never looked back in AlgoRot",
        f"The perfect AlgoRot run that might never be repeated",
        f"This is what happens when the algorithm absolutely cooks",
        f"A W so clean the simulation had to double check it was real",
        f"They absorbed nothing and delivered everything in {f1_name} vs {f2_name}",
        f"The most dominant AlgoRot fighter we have seen all season",
        f"No sweat. No damage. Just results in {f1_name} vs {f2_name}",
        f"A flawless performance that the AlgoRot archive will never forget",
        f"The algorithm decided one fighter was simply better today",
        f"One-sided does not even begin to cover it in {f1_name} vs {f2_name}",
        f"The HP gap at the end tells the whole story in AlgoRot",
        f"A thorough beating from the very first moment in AlgoRot",
        f"This result was never in doubt for a single frame",
        f"The winner cruised and the loser suffered in {f1_name} vs {f2_name}",
        f"Not a close fight. Not even slightly in {f1_name} vs {f2_name}",
        f"The cleanest route to victory AlgoRot has ever charted",
        f"An HP lead that only ever grew in this AlgoRot match",
        f"The gap opened early and it never closed in {f1_name} vs {f2_name}",
        f"One fighter handled this. The other got handled in AlgoRot",
        f"A result written in the first five seconds in AlgoRot",
        f"The domination was quiet. The result was loud in {f1_name} vs {f2_name}",
        f"They outpaced the damage intake from start to finish in AlgoRot",
        f"A comprehensive win in {f1_name} vs {f2_name} that left nothing open",
        f"The algorithm handed one side a complete gift today in AlgoRot",
        f"A slow and methodical destruction in {f1_name} vs {f2_name}",
        f"This level of control does not happen often in AlgoRot",
        f"A performance that made the fight feel like practice in {f1_name} vs {f2_name}",
        f"The margin grew every second in this AlgoRot battle",
        f"They absorbed the fight and gave back double in AlgoRot",
        f"From the jump this was never going to be close in {f1_name} vs {f2_name}",
        f"A smooth and total takeover in {f1_name} vs {f2_name}",
        f"The difference in class was obvious from frame one in AlgoRot",
        f"They were never threatened and that says everything in {f1_name} vs {f2_name}",
        f"The kind of AlgoRot win where you already know the ending",
        f"One side came to fight. The other came to finish in AlgoRot",
        f"The HP bars could not have been more different in {f1_name} vs {f2_name}",
        f"A controlled demolition from start to finish in AlgoRot",
        f"The opposition had chances. They could not convert any of them",
        f"Winning with that much HP left is rare in AlgoRot. This was rare",
        f"An opponent that just could not close the gap in {f1_name} vs {f2_name}",
        f"They dictated the entire fight and the result shows it",
        f"Not every AlgoRot fight is close. This one was the proof",
        f"The dominant fighter here set the tempo and never lost it",
        f"A convincing win that came with plenty of HP to spare",
        f"The fight was decided before the last hit in AlgoRot",
        f"No fightback. No hope. Just a dominant run in {f1_name} vs {f2_name}",
        f"A performance that the loser will be haunted by in AlgoRot",
        f"One of the more comfortable AlgoRot wins you will ever see",
        f"This fighter smelled blood early and never let go in AlgoRot",
        f"A win that was never truly in question in {f1_name} vs {f2_name}",
        f"The most comfortable margin in recent AlgoRot history",
        f"They were simply on another level in {f1_name} vs {f2_name}",
        f"A fight where one side never showed up in AlgoRot",
        f"The damage ratio in this AlgoRot match is genuinely alarming",
        f"Controlled. Clinical. Completely dominant in {f1_name} vs {f2_name}",
        f"The AlgoRot engine handed someone a masterclass today",
        f"A blowout so clean it almost looked polite in {f1_name} vs {f2_name}",
        f"A margin this wide is its own kind of statement in AlgoRot",
    ]

    standard = [
        f"{f1_name} vs {f2_name} ends in SHOCKING Sudden Death",
        f"The physics in this {f1_name} vs {f2_name} match went CRAZY",
        f"10 Parries Later. {f1_name} vs {f2_name} goes Nuclear",
        f"This {f1_name} vs {f2_name} Sudden Death will give you chills",
        f"NO WAY. The {f1_name} vs {f2_name} Match Was Too Close",
        f"Wait until the end of this {f1_name} vs {f2_name} fight",
        f"You will not believe how {f1_name} vs {f2_name} ends",
        f"Are we dreaming? {f1_name} vs {f2_name} goes off the rails",
        f"This collision between {f1_name} and {f2_name} broke the engine",
        f"The most intense rivalry yet in {f1_name} vs {f2_name}",
        f"Pure satisfying chaos in {f1_name} vs {f2_name} Sudden Death",
        f"My brain melted watching {f1_name} vs {f2_name}",
        f"Who are you rooting for? {f1_name} vs {f2_name} Epic Ending",
        f"Gravity stopped working in this {f1_name} vs {f2_name} clash",
        f"The exact moment {f1_name} vs {f2_name} turned into a movie",
        f"This match had absolutely no right to be this entertaining",
        f"The most unpredictable AlgoRot battle of the week",
        f"Neither side could pull away in this wild {f1_name} vs {f2_name} brawl",
        f"The turning point in {f1_name} vs {f2_name} will blow your mind",
        f"A fight so chaotic the simulation had to catch its breath",
        f"Every swing mattered in this insane {f1_name} vs {f2_name} matchup",
        f"AlgoRot served up something special with {f1_name} vs {f2_name}",
        f"The most evenly matched AlgoRot battle in recent memory",
        f"Back and forth chaos all the way to the final blow",
        f"The AlgoRot algorithm absolutely went unhinged in {f1_name} vs {f2_name}",
        f"Two equals going to war. Only one survives in AlgoRot",
        f"This fight had no business being this good",
        f"Completely unpredictable from first hit to last in {f1_name} vs {f2_name}",
        f"The most watched AlgoRot rematch about to happen after this",
        f"The physics engine went full drama mode in {f1_name} vs {f2_name}",
        f"An absolute banger of a match from start to finish",
        f"The moment {f1_name} vs {f2_name} became legendary in AlgoRot",
        f"AlgoRot just generated something that cannot be unseen",
        f"Close. Intense. Chaotic. {f1_name} vs {f2_name} had everything",
        f"The match that made me forget to breathe in {f1_name} vs {f2_name}",
        f"The simulation decided to go full cinematic in this one",
        f"Not a single dull moment in this {f1_name} vs {f2_name} battle",
        f"The most satisfying ending AlgoRot has produced this week",
        f"Nobody could predict this result in {f1_name} vs {f2_name}",
        f"When the algorithm decides to get dramatic in AlgoRot",
        f"A razor-thin margin decided this wild {f1_name} vs {f2_name} fight",
        f"The cleanest AlgoRot chaotic brawl you will see today",
        f"This kind of finish is exactly why AlgoRot has fans",
        f"AlgoRot physics went completely sideways in {f1_name} vs {f2_name}",
        f"Two fighters. One winner. Zero predictability in AlgoRot",
        f"The most dramatic HP race in {f1_name} vs {f2_name} history",
        f"An AlgoRot battle that kept swinging right until the end",
        f"The collision that changed everything in {f1_name} vs {f2_name}",
        f"This is what peak algorithmic combat looks like",
        f"Fighting until nothing is left in {f1_name} vs {f2_name}",
        f"Absolutely zero chill from either fighter in this AlgoRot match",
        f"The most watched fight on the channel is about to be this one",
        f"Total warfare from the first frame in {f1_name} vs {f2_name}",
        f"An AlgoRot matchup that deserves to be studied",
        f"Both fighters showed up prepared to destroy in {f1_name} vs {f2_name}",
        f"The match that defined the entire {f1_name} vs {f2_name} rivalry",
        f"AlgoRot finally gave us the {f1_name} vs {f2_name} match we deserved",
        f"The fight that got away from both sides in AlgoRot",
        f"When the damage numbers get big things get real fast in AlgoRot",
        f"The greatest battle in the {f1_name} vs {f2_name} series so far",
        f"This AlgoRot fight has more plot twists than a short film",
        f"Completely even right up until the moment it was not",
        f"The final exchange in {f1_name} vs {f2_name} is everything",
        f"Mayhem physics and a ridiculous ending in {f1_name} vs {f2_name}",
        f"This is exactly why I watch AlgoRot every single day",
        f"Two unstoppable forces. One unforgettable result in AlgoRot",
        f"The battle that shook the AlgoRot leaderboard in {f1_name} vs {f2_name}",
        f"Sheer aggression from both sides right until the final frame",
        f"Tied on chaos. Decided by physics in {f1_name} vs {f2_name}",
        f"The match that AlgoRot was literally built to generate",
        f"A rivalry match so good it needs a sequel in AlgoRot",
        f"When the HP bars get this close the crowd loses it",
        f"This fight aged five years in thirty seconds in AlgoRot",
        f"The intensity of {f1_name} vs {f2_name} is almost too much",
        f"If you only watch one AlgoRot fight today make it this one",
        f"This outcome in {f1_name} vs {f2_name} made absolutely no sense and yet",
        f"The simulation generated something extraordinary in this match",
        f"When two fighters are this close sparks literally fly in AlgoRot",
        f"The most evenly balanced AlgoRot fight of the entire season",
        f"Neither side blinked in this {f1_name} vs {f2_name} showdown",
        f"The moment this AlgoRot match stopped being normal",
        f"A genuine classic in the making from {f1_name} vs {f2_name}",
        f"When AlgoRot says no mercy it absolutely means it",
        f"This battle had energy from the very first frame in AlgoRot",
        f"The ending of {f1_name} vs {f2_name} will be talked about for days",
        f"AlgoRot has never generated a closer fight than this one",
        f"The most chaotically balanced battle in the entire series",
        f"A fight where every single decision mattered in {f1_name} vs {f2_name}",
        f"Neither fighter wanted to be the one who lost this one",
        f"The algorithm completely lost the plot in {f1_name} vs {f2_name}",
        f"Head-to-head and completely unpredictable in AlgoRot",
        f"The most dramatic trading sequence in {f1_name} vs {f2_name} history",
        f"This AlgoRot match ended in a way nobody in the comments predicted",
        f"A genuinely wild ride from first hit to last breath in AlgoRot",
        f"AlgoRot peaked today and it peaked during {f1_name} vs {f2_name}",
        f"The simulation generated drama and then kept going in AlgoRot",
        f"Equal damage. Unequal endings. The beauty of {f1_name} vs {f2_name}",
        f"The most competitive fight the algorithm has ever produced",
        f"Both fighters threw everything and only one thing remained in AlgoRot",
        f"The AlgoRot simulation just delivered its most chaotic finish yet",
        f"The fight swung so many times it made my head spin in AlgoRot",
        f"A result that could have gone either way right up to the end",
        f"They traded everything and only one walked away in {f1_name} vs {f2_name}",
        f"The most edge-of-your-seat HP race in {f1_name} vs {f2_name}",
        f"This AlgoRot fight went exactly as chaotic as the best ones do",
        f"One wrong move and this entire result changes in {f1_name} vs {f2_name}",
        f"The kind of fight where momentum flipped every few seconds in AlgoRot",
        f"No runaway winner. Just a brutal back-and-forth in {f1_name} vs {f2_name}",
        f"This is the fight type that makes AlgoRot worth watching",
        f"A messy competitive brawl with a clean winner in {f1_name} vs {f2_name}",
        f"Neither fighter could get comfortable in this one in AlgoRot",
        f"The most convincingly competitive {f1_name} vs {f2_name} fight yet",
        f"Both HP bars moved constantly. Only one hit zero first",
        f"A grind of a fight that paid off in the most satisfying way",
        f"The fight felt even. The ending said otherwise in {f1_name} vs {f2_name}",
        f"Both fighters gave it everything in this AlgoRot match",
        f"An AlgoRot fight that earns the rewatch at the end",
        f"Nobody was safe in this {f1_name} vs {f2_name} battle",
        f"The most competitive damage exchange in recent AlgoRot history",
        f"Two fighters refusing to yield in {f1_name} vs {f2_name}",
        f"A genuine war that finally found a winner in AlgoRot",
        f"The fight never settled. Neither did my heartbeat in {f1_name} vs {f2_name}",
        f"A hard-fought result in {f1_name} vs {f2_name} that could easily be reversed",
        f"The closest-feeling fight with this HP gap in AlgoRot",
        f"They pushed each other to the absolute edge in {f1_name} vs {f2_name}",
        f"Every hit felt meaningful in this AlgoRot battle",
        f"An AlgoRot match that rewards you for watching every second",
        f"The fight looked even until suddenly it was not in {f1_name} vs {f2_name}",
        f"This is what peak algorithmic combat looks like",
        f"A fight that neither side dominated and only one side won",
        f"The tension in this {f1_name} vs {f2_name} match never fully broke",
        f"A winner emerged but both fighters earned their moment in AlgoRot",
        f"The most satisfying mid-range finish in {f1_name} vs {f2_name}",
        f"No one was pulling away and then suddenly someone was in AlgoRot",
        f"An AlgoRot battle with genuine momentum shifts throughout",
        f"Both fighters came to win and only physics could separate them",
        f"A fight with real drama hidden in the middle of it in AlgoRot",
        f"The HP stayed close for so long the ending hit different in {f1_name} vs {f2_name}",
        f"Two fighters. Equal hunger. One algorithm. AlgoRot decides",
        f"The winner here had to actually earn it in {f1_name} vs {f2_name}",
        f"This AlgoRot fight was never going to be easy and it was not",
        f"A competitive result that the winner had to fight hard for",
        f"The simulation built something genuinely entertaining in {f1_name} vs {f2_name}",
        f"An AlgoRot fight that made both outcomes feel possible",
        f"The most evenly contested {f1_name} vs {f2_name} in the series",
        f"A fight decided by the smallest edge in the biggest moment",
        f"When both fighters are this committed something has to give in AlgoRot",
        f"The HP gap told a story. The fight told a better one in {f1_name} vs {f2_name}",
        f"AlgoRot came through with a proper competitive fight today",
        f"The kind of AlgoRot match that makes you want to run it back immediately",
    ]

    stomp = [
        f"An absolutely untouchable performance in {f1_name} vs {f2_name}",
        f"They finished with over half their HP. This was never close",
        f"A surgical dismantling in {f1_name} vs {f2_name}",
        f"This is what a perfect AlgoRot run looks like",
        f"The opponent never even dented them in {f1_name} vs {f2_name}",
        f"Running at near-full health through an entire fight in AlgoRot",
        f"The most dominant margin of victory in AlgoRot this season",
        f"They barely took any damage in {f1_name} vs {f2_name}",
        f"An efficiency rating this high should be illegal in AlgoRot",
        f"The cleanest win condition the algorithm has ever produced",
        f"Zero drama. Maximum destruction in {f1_name} vs {f2_name}",
        f"Like they were not even fighting the same battle in AlgoRot",
        f"The opponent landed nothing of consequence in {f1_name} vs {f2_name}",
        f"A walking health bar making a statement in AlgoRot",
        f"The most one-sided HP gap in {f1_name} vs {f2_name} history",
        f"Walked in fresh. Walked out fresher. AlgoRot perfection",
        f"Nearly untouched from start to finish in {f1_name} vs {f2_name}",
        f"The cleanest margin this AlgoRot simulation has ever generated",
        f"This performance was not a fight. It was a demonstration",
        f"AlgoRot produced the most efficient fighter on record in {f1_name} vs {f2_name}",
        f"The most pristine health bar after a win in AlgoRot",
        f"They finished the fight almost completely undamaged",
        f"A 60 plus percent HP finish. Someone just got embarrassed in AlgoRot",
        f"The opponent hit them once and that was the highlight in {f1_name} vs {f2_name}",
        f"An AlgoRot run this clean has never been seen before",
        f"Entered at full health. Left at almost full health. Won anyway",
        f"The most dominant performance without breaking a sweat in AlgoRot",
        f"A victory lap disguised as a fight in {f1_name} vs {f2_name}",
        f"The HP bar barely moved on one side in this AlgoRot match",
        f"Completely untouchable from the opening frame in AlgoRot",
        f"The most lopsided HP remaining gap in {f1_name} vs {f2_name}",
        f"They looked like a tutorial boss fighting a beginner in AlgoRot",
        f"Not a scratch. Not a care. A dominant win in AlgoRot",
        f"The physics could not touch them in {f1_name} vs {f2_name}",
        f"This is what maximum efficiency looks like in AlgoRot",
        f"A performance so clinical it felt calculated by design",
        f"The highest HP finish AlgoRot has recorded this season in {f1_name} vs {f2_name}",
        f"This was never a fight. It was always an execution",
        f"The most lopsided finish in {f1_name} vs {f2_name} to date",
        f"The algorithm made one fighter look like a god today",
        f"Barely breathed heavily through the entire fight in AlgoRot",
        f"A near-perfect run in {f1_name} vs {f2_name} that redefines dominance",
        f"The opponent had no answer for this fighter at all in AlgoRot",
        f"The definition of effortless in {f1_name} vs {f2_name}",
        f"An HP bar so full after the fight it seemed wrong in AlgoRot",
        f"Dealt everything. Absorbed nothing. Perfection in {f1_name} vs {f2_name}",
        f"The most impenetrable fighter the algorithm has ever generated",
        f"Not just a win. A statement. AlgoRot crowns a new standard",
        f"This fighter took almost zero punishment in {f1_name} vs {f2_name}",
        f"A dominant performance that sets a new AlgoRot benchmark",
        f"The cleanest HP gap between winner and loser in AlgoRot history",
        f"An opponent who never figured out how to land a hit in {f1_name} vs {f2_name}",
        f"Walking into a fight invincible and walking out proving it in AlgoRot",
        f"The most comfortable win the algorithm has ever simulated",
        f"They could have fought two of them and still looked like this",
        f"A high HP finish so rare AlgoRot had to double check it",
        f"The most complete performance in {f1_name} vs {f2_name} history",
        f"An untouchable result that no simulation should be able to produce",
        f"They were not competing. They were showcasing in AlgoRot",
        f"The kind of finish that makes the other fighter question everything in {f1_name} vs {f2_name}",
        f"The best HP conservation in AlgoRot match history",
        f"An AlgoRot fighter operating at maximum capacity",
        f"Left the fight healthier than most fighters enter in {f1_name} vs {f2_name}",
        f"The algorithm designed a perfect fighter for this round in AlgoRot",
        f"Absorbing almost nothing while delivering total destruction",
        f"A high HP victory that proves not all weapons are equal in AlgoRot",
        f"The most effortless AlgoRot win of the entire season",
        f"This fighter exists in a different tier from everyone else in AlgoRot",
        f"The cleanest technical performance AlgoRot has generated yet",
        f"Maximum output. Minimum input. The AlgoRot formula perfected",
        f"A lopsided HP finish that speaks for itself in {f1_name} vs {f2_name}",
        f"The opponent existed. They did not matter. AlgoRot is brutal",
        f"They barely needed the full duration to prove a point in AlgoRot",
        f"A near-flawless health record after a full fight in {f1_name} vs {f2_name}",
        f"The most intact health bar after battle in AlgoRot this year",
        f"They showed up and did not let anything touch them in {f1_name} vs {f2_name}",
        f"The damage output was overwhelming. The damage received was nothing",
        f"AlgoRot just generated the most dominant champion yet",
        f"A performance that makes the leaderboard look unfair in {f1_name} vs {f2_name}",
        f"Controlled the entire fight without ever being in danger in AlgoRot",
        f"The most one-sided HP differential in this AlgoRot matchup series",
        f"A fighter running at peak efficiency in {f1_name} vs {f2_name}",
        f"So dominant the fight felt like a setup in AlgoRot",
        f"The kind of win that resets everyone's expectations in AlgoRot",
        f"A machine-like performance in {f1_name} vs {f2_name}",
        f"The best efficiency rating in AlgoRot this entire season",
        f"Not just winning. Winning without consequence in {f1_name} vs {f2_name}",
        f"The most overpowered round result in AlgoRot to date",
        f"They made the simulation look like a practice run in {f1_name} vs {f2_name}",
        f"An untouchable margin that the AlgoRot archive will remember",
        f"The benchmark run that all future AlgoRot fighters will be compared to",
        f"A fight so one-sided physics barely got involved in {f1_name} vs {f2_name}",
        f"The cleanest clean sweep in {f1_name} vs {f2_name} history",
        f"Running on full power from start to finish in AlgoRot",
        f"Practically glowing with health after the fight in {f1_name} vs {f2_name}",
        f"The fighter that turned an AlgoRot match into a training session",
        f"A supremacy run so clean it almost felt wrong to watch",
        f"The highest HP differential the AlgoRot engine has ever produced",
        f"Total control from start to finish in {f1_name} vs {f2_name}",
        f"The algorithm created a monster today in {f1_name} vs {f2_name}",
    ]

    wire_to_wire = [
        f"Never trailed. Never in doubt. {f1_name} vs {f2_name}",
        f"The most dominant wire-to-wire win in AlgoRot",
        f"They took the lead on hit one and kept it forever",
        f"A masterclass in holding a lead in {f1_name} vs {f2_name}",
        f"They never looked back after the first collision",
        f"Total control from the absolute start in AlgoRot",
        f"Leading every single frame of {f1_name} vs {f2_name}",
        f"A wire-to-wire victory that proves who the boss is",
        f"The opponent never had the lead. Not for a second",
        f"Front-running to perfection in {f1_name} vs {f2_name}",
        f"The wire-to-wire run that everyone will be talking about",
        f"A clean sweep of the momentum in {f1_name} vs {f2_name}",
        f"Zero lead changes. One absolute victor in AlgoRot",
        f"The gap opened early and stayed open the entire time",
        f"They grabbed the wheel and never let go in {f1_name} vs {f2_name}",
        f"Leading from the opening bell to the final blow",
        f"A pure wire-to-wire clinic in {f1_name} vs {f2_name}",
        f"They established dominance instantly and held it",
        f"The other fighter was playing catch-up the entire time",
        f"A flawless front-running performance in AlgoRot",
        f"They took pole position and never gave it back",
        f"One-way traffic from the very first second",
        f"An absolute lock from the start in {f1_name} vs {f2_name}",
        f"No lead changes allowed in this AlgoRot masterclass",
        f"They set the pace and the opponent could not keep up",
        f"Wire-to-wire supremacy in {f1_name} vs {f2_name}",
        f"The most unbothered lead hold in AlgoRot history",
        f"They jumped ahead and simply stayed there",
        f"A wire-to-wire performance that broke the opponent's spirit",
        f"Leading the entire way without breaking a sweat",
        f"The opponent spent the whole match looking at their back",
        f"From frame one to the end it was all them",
        f"A classic wire-to-wire domination in {f1_name} vs {f2_name}",
        f"They claimed the lead early and guarded it perfectly",
        f"Never behind on the scoreboard for a single moment",
        f"The most secure wire-to-wire run we have seen yet",
        f"They dictated the terms from the very beginning",
        f"An unbreakable lead maintained from start to finish",
        f"Leading the dance from the first step in AlgoRot",
        f"A textbook wire-to-wire victory in {f1_name} vs {f2_name}",
        f"The opponent never saw the front in this match",
        f"Taking control early and refusing to let it go",
        f"A wire-to-wire showcase of pure control",
        f"They were ahead before the opponent even settled in",
        f"Never trailed. Never panicked. Pure execution",
        f"A wire-to-wire statement game in {f1_name} vs {f2_name}",
        f"The lead was established and then heavily defended",
        f"They did not trail for a single millisecond in AlgoRot",
        f"A start-to-finish lead that demoralized the opponent",
        f"Leading from the very first frame of {f1_name} vs {f2_name}",
        f"The most comfortable wire-to-wire win possible",
        f"They grabbed the momentum instantly and kept it forever",
        f"A wire-to-wire run that looked completely effortless",
        f"The opponent was essentially a spectator to this lead",
        f"Holding the high ground from beginning to end",
        f"A flawless wire-to-wire execution in AlgoRot",
        f"They made front-running look incredibly easy today",
        f"Never in the rearview mirror. Always leading",
        f"A wire-to-wire beatdown in {f1_name} vs {f2_name}",
        f"The lead was theirs from the very first exchange",
        f"A masterclass in maintaining an early advantage",
        f"They set the bar high early and stayed above it",
        f"A wire-to-wire run built on pure consistency",
        f"The opponent never even tied the game up once",
        f"Leading the entire match like it was a practice run",
        f"A wire-to-wire performance for the AlgoRot archives",
        f"They claimed the driver's seat immediately",
        f"An early lead converted into a flawless wire-to-wire win",
        f"The most convincing start-to-finish win this season",
        f"They were ahead the entire time and everyone knew it",
        f"A wire-to-wire victory completely devoid of drama",
        f"The opponent chased ghosts the entire match",
        f"A wire-to-wire sweep of the match timeline",
        f"They locked in the lead and threw away the key",
        f"Leading every moment of {f1_name} vs {f2_name}",
        f"A wire-to-wire win that leaves absolutely zero doubt",
        f"The most authoritative start-to-finish win in AlgoRot",
        f"They jumped the gun and won the entire race",
        f"A wire-to-wire lock down performance",
        f"The opponent was never in the lead. Never",
        f"Taking the reins early and driving it home",
        f"A perfect wire-to-wire simulation in {f1_name} vs {f2_name}",
        f"They owned the lead for 100 percent of the match",
        f"A wire-to-wire masterstroke in AlgoRot history",
        f"The lead never wavered. Not for a second",
        f"A wire-to-wire run that completely stifled the opposition",
        f"They were the frontrunner from the absolute start",
        f"A wire-to-wire statement piece in {f1_name} vs {f2_name}",
        f"Leading from the opening whistle to the final frame",
        f"A wire-to-wire performance that defined the matchup",
        f"They never let the opponent even taste the lead",
        f"A start-to-finish clinic in {f1_name} vs {f2_name}",
        f"The lead was unshakeable from the very beginning",
        f"A wire-to-wire victory lap in AlgoRot",
        f"They led for every single tick of the clock",
        f"A wire-to-wire win that was never in jeopardy",
        f"The opponent's lead time in this match was exactly zero",
        f"A wire-to-wire masterpiece in {f1_name} vs {f2_name}",
        f"They took the lead on the first frame and never gave it back",
        f"A wire-to-wire domination that speaks for itself",
    ]

    comeback = [
        f"The most insane comeback in {f1_name} vs {f2_name}",
        f"They were down BAD. Then this happened",
        f"A legendary rally from the brink of defeat",
        f"The greatest comeback in AlgoRot history",
        f"How did they come back from that deficit?",
        f"Down massive and still pulling off the W",
        f"The comeback of the century in {f1_name} vs {f2_name}",
        f"They flipped the script completely in AlgoRot",
        f"A comeback so good it looks scripted",
        f"Never give up. The ultimate {f1_name} vs {f2_name} comeback",
        f"The momentum shift that broke the simulation",
        f"A comeback run that will be studied in AlgoRot",
        f"They clawed back from nothing in {f1_name} vs {f2_name}",
        f"From completely out of it to walking away the winner",
        f"The ultimate underdog comeback in {f1_name} vs {f2_name}",
        f"A monumental rally when all hope seemed lost",
        f"They woke up just in time to steal the victory",
        f"The most improbable turnaround of the entire season",
        f"Down bad but absolutely not out in AlgoRot",
        f"A comeback that defied every single probability metric",
        f"They snatched victory straight out of the fire",
        f"The comeback arc in this match is generational",
        f"From the depths of defeat to the top of the podium",
        f"A staggering turnaround in {f1_name} vs {f2_name}",
        f"They refused to stay down when it mattered most",
        f"The greatest second-half surge we have ever seen",
        f"A comeback built on pure adrenaline and willpower",
        f"They were completely counted out before this rally",
        f"The most jaw-dropping comeback run in AlgoRot",
        f"A deficit erased in the blink of an eye",
        f"They came back from a virtually impossible position",
        f"The momentum swung so hard it caused whiplash",
        f"A legendary comeback that will break the internet",
        f"They weathered the storm and brought the thunder",
        f"From almost eliminated to completely victorious",
        f"The comeback story that AlgoRot fans needed",
        f"They fought their way out of an inescapable hole",
        f"A miraculous recovery in {f1_name} vs {f2_name}",
        f"The most resilient performance in AlgoRot history",
        f"They wiped away a massive lead like it was nothing",
        f"A comeback so impossible it feels like a glitch",
        f"Rising from the ashes to take the crown",
        f"They were essentially dead before this epic rally",
        f"A turnaround that makes absolutely zero logical sense",
        f"The most heroic comeback effort in {f1_name} vs {f2_name}",
        f"They flipped a guaranteed loss into a massive win",
        f"A comeback that proves you can never celebrate early",
        f"They erased the deficit with terrifying speed",
        f"The greatest underdog rally in the AlgoRot archives",
        f"From the edge of the abyss to total victory",
        f"A comeback that completely rewired the match",
        f"They staged an uprising against the scoreboard",
        f"The most explosive turnaround we have witnessed",
        f"A deficit this large should not be survivable",
        f"They pulled off the impossible comeback in AlgoRot",
        f"From a sure defeat to an unbelievable triumph",
        f"The comeback engine turned on at the perfect time",
        f"A rally so fierce the opponent forgot how to fight",
        f"They dismantled a massive lead piece by piece",
        f"The most stubborn comeback in {f1_name} vs {f2_name}",
        f"A reverse sweep of the match's entire momentum",
        f"They refused the loss and chose violence instead",
        f"The comeback that silenced everyone watching",
        f"From rock bottom to the highest peak in seconds",
        f"A monumental recovery when the odds were zero",
        f"They woke up and chose to rewrite the ending",
        f"The most chaotic comeback in AlgoRot this year",
        f"A rally that belongs in the history books",
        f"They climbed an impossible mountain to win this",
        f"The comeback that broke the opponent's brain",
        f"From life support to lifting the trophy",
        f"A turnaround that left the simulation stunned",
        f"They stole this win from the jaws of certain doom",
        f"The most spectacular comeback sequence ever",
        f"A deficit completely vaporized in record time",
        f"They launched a counterattack that changed everything",
        f"The comeback of a lifetime in {f1_name} vs {f2_name}",
        f"From fully defeated to standing over the opponent",
        f"A rally fueled by absolute refusal to lose",
        f"They flipped the board over and won the game",
        f"The most devastating comeback for the opponent",
        f"A turnaround so sharp it defied physics",
        f"They clawed out of a grave to win this match",
        f"The greatest comeback sprint in AlgoRot history",
        f"From an insurmountable deficit to a clean win",
        f"A comeback so wild it feels completely illegal",
        f"They erased the opponent's lead like chalk",
        f"The most unbelievable second wind in AlgoRot",
        f"A rally that shattered all expectations",
        f"They came back from the void to take the W",
        f"The comeback that defines this entire rivalry",
        f"From absolutely nowhere to winning everything",
        f"A turnaround that proves stats are meaningless",
        f"They ripped the victory away at the last moment",
        f"The most iconic comeback in {f1_name} vs {f2_name}",
        f"A rally that will be remembered for generations",
        f"They engineered a comeback that belongs in a museum",
        f"From negative momentum to an unstoppable force",
        f"The greatest comeback the algorithm has ever seen",
    ]

    choke = [
        f"The biggest throw in AlgoRot history",
        f"They had a massive lead and CHOKED it",
        f"How do you lose from there? {f1_name} vs {f2_name}",
        f"The most painful choke ever caught on simulation",
        f"Blowing a giant lead in {f1_name} vs {f2_name}",
        f"They threw the whole match away in AlgoRot",
        f"The biggest lead thrown away this season",
        f"A historic choke job in {f1_name} vs {f2_name}",
        f"From guaranteed win to total embarrassment",
        f"They completely choked the bag in AlgoRot",
        f"A massive lead erased in seconds in {f1_name} vs {f2_name}",
        f"The throw of the century in the AlgoRot arena",
        f"Watching a huge lead evaporate in real time",
        f"They fumbled the victory spectacularly in {f1_name} vs {f2_name}",
        f"A choke so bad it needs to be investigated",
        f"The most monumental collapse we have ever seen",
        f"They had it in the bag and completely dropped it",
        f"A legendary throw that will live in infamy",
        f"How did they manage to fumble this victory?",
        f"The biggest bottle job in AlgoRot history",
        f"They snatched defeat from the jaws of victory",
        f"A massive lead completely squandered in seconds",
        f"The choke of a lifetime in {f1_name} vs {f2_name}",
        f"They fell apart at the absolute worst moment",
        f"A catastrophic collapse that defies all logic",
        f"They choked away a lead that should be unlosable",
        f"The most embarrassing throw in recent memory",
        f"A colossal fumble when the win was guaranteed",
        f"They handed the match away on a silver platter",
        f"The choke that will haunt them forever",
        f"A monumental breakdown in {f1_name} vs {f2_name}",
        f"They melted down when they had the game won",
        f"The biggest choke job the simulation has ever generated",
        f"A lead so large it should have been impossible to blow",
        f"They tripped over the finish line and lost",
        f"The most devastating collapse in AlgoRot this year",
        f"A throw so bad it feels intentionally scripted",
        f"They folded completely under absolutely zero pressure",
        f"The greatest fumble of a guaranteed victory",
        f"A choke that belongs in the AlgoRot hall of shame",
        f"They gave away a lead that was built like a fortress",
        f"The most incomprehensible throw of the season",
        f"A complete capitulation in {f1_name} vs {f2_name}",
        f"They dropped the ball right at the goal line",
        f"The choke that broke the internet's brain",
        f"A massive advantage completely flushed away",
        f"They completely unravelled in the final moments",
        f"The worst throw in the history of this matchup",
        f"A monumental choke that defies all mathematics",
        f"They managed to lose a truly unlosable game",
        f"The most tragic collapse we have ever witnessed",
        f"A fumble of epic proportions in {f1_name} vs {f2_name}",
        f"They essentially gifted the opponent the victory",
        f"The choke job that everyone is talking about",
        f"A catastrophic error in closing out the match",
        f"They crumbled completely when it counted",
        f"The biggest bag drop in AlgoRot history",
        f"A lead blown so spectacularly it is almost impressive",
        f"They threw away the game of their lives",
        f"The most legendary choke of the entire series",
        f"A monumental failure to secure the victory",
        f"They folded like a cheap suit with a massive lead",
        f"The worst possible time to completely forget how to fight",
        f"A choke that will be studied as a cautionary tale",
        f"They let a historic lead slip through their fingers",
        f"The most mind-boggling throw in AlgoRot",
        f"A complete shutdown of their own winning strategy",
        f"They fumbled the easiest win of the season",
        f"The choke that left the commentators speechless",
        f"A massive lead vanished into absolute thin air",
        f"They managed to ruin a perfectly good domination",
        f"The greatest collapse the algorithm has ever produced",
        f"A throw so massive it has its own gravitational pull",
        f"They completely choked when the spotlight was on",
        f"The most spectacular self-destruction in AlgoRot",
        f"A fumble that completely rewrote the matchup's history",
        f"They gave up a lead that required effort to lose",
        f"The worst bottle job of the entire tournament",
        f"A monumental choke that defies explanation",
        f"They threw the win away and handed over the crown",
        f"The most painful way to lose a match in AlgoRot",
        f"A complete evaporation of a guaranteed win",
        f"They managed to snatch a loss from a certain victory",
        f"The choke that will be replayed forever",
        f"A colossal throw that ruined a perfect run",
        f"They gave the match away when it was already over",
        f"The most dramatic collapse in {f1_name} vs {f2_name}",
        f"A throw that proves no lead is ever truly safe",
        f"They completely derailed their own victory train",
        f"The biggest choke in the history of the simulation",
        f"A lead completely squandered in the most embarrassing way",
        f"They found the one way to lose and executed it perfectly",
        f"The most devastating fumble of the entire year",
        f"A monumental throw that stunned the entire arena",
        f"They completely panicked with the win in their hands",
        f"The worst choke job the AlgoRot engine has seen",
        f"A massive collapse that will go down in infamy",
        f"They threw a game they had completely dominated",
        f"The choke that redefines the meaning of throwing",
        f"A lead so large losing it feels like a glitch",
    ]

    contested = [
        f"The lead changed so many times my head is spinning",
        f"A back-and-forth war in {f1_name} vs {f2_name}",
        f"The most heavily contested battle of the day",
        f"Neither fighter could hold the lead for long",
        f"A true tug-of-war in {f1_name} vs {f2_name}",
        f"The lead traded hands over and over in AlgoRot",
        f"Nobody wanted to lose this back-and-forth classic",
        f"The most contested match in recent AlgoRot memory",
        f"Constantly shifting momentum in {f1_name} vs {f2_name}",
        f"A chaotic back-and-forth brawl that went the distance",
        f"The definition of a slugfest in {f1_name} vs {f2_name}",
        f"Trading leads until the very last hit in AlgoRot",
        f"A perfectly matched tug-of-war in {f1_name} vs {f2_name}",
        f"Both fighters fought for the lead and neither kept it",
        f"The most balanced chaos AlgoRot can produce",
        f"A seesaw battle that left everyone breathless",
        f"The lead bounced back and forth like a ping pong ball",
        f"An absolute rollercoaster of a matchup in AlgoRot",
        f"They traded blows and leads all match long",
        f"The most fiercely contested fight of the season",
        f"A pendulum swinging wildly between two fighters",
        f"Momentum shifted every single time they collided",
        f"A genuine coin flip of a match right to the end",
        f"The lead changed hands more times than I can count",
        f"An evenly matched brawl that refused to settle",
        f"A tug-of-war where the rope was constantly snapping",
        f"They fought tooth and nail for every inch of the lead",
        f"The most chaotic back-and-forth in {f1_name} vs {f2_name}",
        f"A match defined by constant and brutal lead changes",
        f"Neither fighter was willing to yield an inch",
        f"A true slugfest where the advantage flipped constantly",
        f"The lead was a hot potato neither could hold onto",
        f"An absolute dogfight in the AlgoRot arena",
        f"They swapped the lead so fast it caused motion sickness",
        f"The most tightly contested battle we have ever witnessed",
        f"A seesaw war that had no clear winner until the end",
        f"Momentum was practically a myth in this chaotic fight",
        f"They traded the driver's seat every few seconds",
        f"A back-and-forth classic that defines AlgoRot",
        f"The lead was rented, never owned, in this match",
        f"An incredibly close battle defined by constant swings",
        f"They fought over the lead like a scrap of meat",
        f"The most volatile match in the history of the simulation",
        f"A rollercoaster ride with zero brakes in {f1_name} vs {f2_name}",
        f"Neither side could string together a sustained run",
        f"A match where every hit completely flipped the script",
        f"The lead changed hands at a dizzying pace",
        f"An all-out war with a constantly shifting front line",
        f"They played hot potato with the match advantage",
        f"The most disputed lead in the history of AlgoRot",
        f"A tug-of-war battle that nearly snapped the simulation",
        f"The advantage swung back and forth like a pendulum",
        f"An absolute classic of a contested match",
        f"They traded heavy blows and the lead equally",
        f"The most unstable momentum we have seen this year",
        f"A seesaw brawl that kept everyone guessing",
        f"The lead flipped so often it became meaningless",
        f"A chaotic war of attrition with constant shifts",
        f"Neither fighter could establish real dominance",
        f"A match that swung wildly from one side to the other",
        f"The lead was basically up for grabs every single frame",
        f"An intensely contested slugfest in {f1_name} vs {f2_name}",
        f"They swapped control of the match constantly",
        f"The most evenly traded battle of the entire tournament",
        f"A back-and-forth thriller that delivered on all fronts",
        f"The momentum was a pendulum swinging out of control",
        f"An epic tug-of-war between two perfectly matched foes",
        f"They fought a relentless war over a shifting lead",
        f"The most chaotic power struggle in AlgoRot history",
        f"A match where no advantage lasted more than seconds",
        f"The lead was constantly contested and never secured",
        f"An absolute barnburner of a back-and-forth fight",
        f"They traded the upper hand like it was currency",
        f"The most violently contested match of the season",
        f"A seesaw struggle that refused to name a victor early",
        f"The momentum shifted like the wind in a hurricane",
        f"An incredibly volatile battle in {f1_name} vs {f2_name}",
        f"They fought a bitter war over a fleeting lead",
        f"The most dizzying array of lead changes we have seen",
        f"A match defined by its absolute lack of stability",
        f"The lead bounced between them endlessly",
        f"A chaotic and deeply contested brawl to the finish",
        f"Neither combatant could hold the line for long",
        f"The most balanced and brutal back-and-forth yet",
        f"A match that swung on every single collision",
        f"The advantage was constantly in dispute",
        f"An absolute classic of constantly shifting fortunes",
        f"They traded momentum swings of epic proportions",
        f"The most heavily disputed match in AlgoRot",
        f"A rollercoaster battle that left no room to breathe",
        f"The lead changed so often the tracker broke",
        f"A back-and-forth war that will go down in history",
        f"Neither side could maintain a grip on the match",
        f"The most fiercely debated lead in the simulation",
        f"A completely unpredictable seesaw of a fight",
        f"They fought a literal tug-of-war over the victory",
        f"The most aggressively contested bout we have witnessed",
        f"A match where the lead was a completely fluid concept",
        f"They traded the advantage back and forth relentlessly",
        f"The most chaotic and contested slugfest of the year",
    ]

    return {
        "ghost": ghost,
        "clutch": clutch,
        "standard": standard,
        "blowout": blowout,
        "stomp": stomp,
        "wire_to_wire": wire_to_wire,
        "comeback": comeback,
        "choke": choke,
        "contested": contested,
    }