"""
Title pools for AlgoRot match results.
Categories:
  ghost    - exactly 0% HP left (phantom victory, rarest outcome)
  clutch   - 1-10% HP left (nail-biting survival)
  standard - 11-39% HP left (competitive, back-and-forth)
  blowout  - 40-59% HP left (dominant win)
  stomp    - 60%+ HP left (near-perfect, untouchable run)
No ellipsis (...) or colons (:) in any title.
"""


def get_title_pools(f1_name, f2_name):
    """Return title pools dict keyed by category."""

    ghost = [
        f"The 0 HP win that should not exist in {f1_name} vs {f2_name}",
        f"Technically on zero and still standing in AlgoRot",
        f"Physics said 0. The fighter said otherwise",
        f"A ghost win. Zero HP and somehow still here",
        f"The simulation registered zero and kept going anyway",
        f"Zero HP. Full victory. AlgoRot defies its own rules",
        f"They flatlined and still crossed the finish line",
        f"This is not possible but it just happened in {f1_name} vs {f2_name}",
        f"The most impossible win in AlgoRot runs on HP it does not have",
        f"0 HP on the bar. W in the record. The simulation is broken",
        f"The ghost run that rewrote the AlgoRot rulebook",
        f"Running on negative HP energy in {f1_name} vs {f2_name}",
        f"A victory built on absolutely nothing but will",
        f"The HP bar hit zero and the fighter kept going",
        f"There should be a law against surviving on this in AlgoRot",
        f"They had no HP. The scoreboard did not agree with that",
        f"Zero is a number. It is also apparently enough to win",
        f"The AlgoRot match that made the developers question everything",
        f"A 0 HP victory so rare it might never happen again",
        f"The sim said dead. The algorithm said let them cook",
        f"Surviving on nothing and winning on everything in AlgoRot",
        f"The fighter that the HP bar forgot to kill in {f1_name} vs {f2_name}",
        f"No HP left. No problem. No explanation in AlgoRot",
        f"Zero on the clock and zero on the bar. One of them walks out anyway",
        f"This is either a miracle or a bug and it does not matter which",
        f"The last tick of HP and somehow it was enough in {f1_name} vs {f2_name}",
        f"A phantom victory that the leaderboard will never forget",
        f"They should have been deleted. They were not",
        f"Running on vibes and 0 HP in {f1_name} vs {f2_name}",
        f"The fight was over. Someone forgot to tell the fighter",
        f"Zero HP. Not zero will. AlgoRot proves math is optional",
        f"This is the rarest outcome in AlgoRot history",
        f"The most technically dead winner in {f1_name} vs {f2_name}",
        f"A win that required exactly zero HP and infinite spirit",
        f"The HP bar begged them to stop. They refused",
        f"Existing past the point of logic in {f1_name} vs {f2_name}",
        f"The zero HP special. A legendary rarity in AlgoRot",
        f"This fighter borrowed HP from the next dimension",
        f"A scoreline that should not be legal in AlgoRot",
        f"They were at zero. They still won. AlgoRot has no rules",
        f"The most statistically improbable win in {f1_name} vs {f2_name}",
        f"The HP display showed nothing. The W display showed everything",
        f"Fighting past the HP limit in {f1_name} vs {f2_name}",
        f"The ghost walk victory that AlgoRot fans will talk about forever",
        f"Technically eliminated. Actually victorious. AlgoRot does it again",
        f"When the simulation refuses to let you lose in {f1_name} vs {f2_name}",
        f"A 0 HP performance so absurd it deserves a trophy",
        f"Dying on paper. Winning on the scoreboard. AlgoRot math",
        f"The least amount of HP ever used to win in AlgoRot",
        f"A finish line crossed with nothing left in the tank",
        f"They had 0 and made it count in {f1_name} vs {f2_name}",
        f"The shadow victory. No HP. All heart in AlgoRot",
        f"This is what winning looks like when physics stops working",
        f"An AlgoRot win powered entirely by unexplained forces",
        f"The simulation glitched. The victory was real in {f1_name} vs {f2_name}",
        f"The most technically wrong winner in AlgoRot and yet",
        f"A champion that the HP bar already gave up on",
        f"0 percent HP. 100 percent victory. AlgoRot refuses logic",
        f"The void cannot stop this fighter in {f1_name} vs {f2_name}",
        f"Running on borrowed time and crossing the finish line anyway",
        f"This win should be studied in every physics class in AlgoRot",
        f"The moment the simulation said wait a second in {f1_name} vs {f2_name}",
        f"Existing at 0 HP and still having the audacity to win",
        f"A victory forged from pure stubbornness in AlgoRot",
        f"The most haunting win condition in {f1_name} vs {f2_name}",
        f"There is no HP left. There is only the win",
        f"AlgoRot finally produced the impossible 0 HP win",
        f"This fighter did not get the memo about having zero HP",
        f"The luckiest bracket in AlgoRot goes to {f1_name} vs {f2_name}",
        f"Hollow and victorious in {f1_name} vs {f2_name}",
        f"The deadliest 0 HP fighter AlgoRot has ever generated",
        f"A result that broke the leaderboard and the laws of physics",
        f"You cannot kill what refuses to check its own HP bar",
        f"This match ended at zero and started a legend in AlgoRot",
        f"The most unexpected survivor in {f1_name} vs {f2_name} history",
        f"Zero. That is the HP. That is also apparently enough",
        f"A ghost of a win in {f1_name} vs {f2_name} that will never fade",
        f"The 0 HP special that AlgoRot saved for the right moment",
        f"The emptiest HP bar. The fullest victory in AlgoRot",
        f"Summoning a win from literally nothing in {f1_name} vs {f2_name}",
        f"The match that proved HP is just a suggestion in AlgoRot",
        f"A round that ended at zero and launched a legend",
        f"Nobody with 0 HP has ever won like this in AlgoRot",
        f"Flatline energy. Championship result in {f1_name} vs {f2_name}",
        f"The zero percent survival rate just became one hundred",
        f"A hollow fighter with a very full record in AlgoRot",
        f"The simulation ran out of HP before it ran out of fight",
        f"Crossing the finish line with the tanks completely empty",
        f"This is AlgoRot at its most unhinged and we love it",
        f"The rarest 0 HP win in the entire AlgoRot archive",
        f"An outcome so unlikely the simulation had to run it twice",
        f"A title earned with absolutely zero HP to spare in AlgoRot",
        f"The fight is over. Nobody told the winner in {f1_name} vs {f2_name}",
        f"Winning from the grave in {f1_name} vs {f2_name}",
        f"No health. No problem. A legendary moment in AlgoRot",
        f"The 0 HP win that turns a round into a story",
        f"This victory should have required more HP. It did not",
        f"At exactly zero and still the last one standing in AlgoRot",
        f"The most ghost energy win in {f1_name} vs {f2_name} all season",
        f"A fighter technically dead and practically unstoppable in AlgoRot",
    ]

    clutch = [
        f"The greatest 1 HP comeback in AlgoRot history",
        f"Someone actually survived on 1 HP in {f1_name} vs {f2_name}",
        f"Never count them out. INSANE Ending in {f1_name} vs {f2_name}",
        f"They thought it was over. Wait for it",
        f"The Ultimate Underdog Story in {f1_name} vs {f2_name}",
        f"A literal miracle in the final seconds of {f1_name} vs {f2_name}",
        f"Greatest Plot Twist. Someone refuses to die",
        f"99 percent of people thought this was over. Then they woke up",
        f"How did they survive that? (1 HP Comeback in {f1_name} vs {f2_name})",
        f"A massive lead just got CHOKED in {f1_name} vs {f2_name}",
        f"The exact moment the tables turned in {f1_name} vs {f2_name}",
        f"The craziest buzzer-beater win yet in AlgoRot",
        f"From the brink of defeat. A legendary clutch in {f1_name} vs {f2_name}",
        f"Do not swipe away. This comeback is pure cinema",
        f"{f1_name} vs {f2_name} goes down to the wire",
        f"This should have been over in 10 seconds. It was not",
        f"The comeback nobody saw coming in {f1_name} vs {f2_name}",
        f"1 HP left and they STILL found a way to win",
        f"The most dramatic survival moment in AlgoRot history",
        f"Bro really said no to dying. {f1_name} vs {f2_name}",
        f"This is the most stressful 30 seconds in AlgoRot",
        f"They had one HP. ONE. And they still won",
        f"The crowd would have gone absolutely insane for this one",
        f"The underdog win that broke every prediction",
        f"When the algorithm refuses to give up. {f1_name} vs {f2_name}",
        f"You will not believe who survives in {f1_name} vs {f2_name}",
        f"Down bad and STILL clutching up in {f1_name} vs {f2_name}",
        f"This HP was so low it should have been illegal",
        f"The last possible moment comeback in {f1_name} vs {f2_name}",
        f"Thought it was over? Think again. {f1_name} vs {f2_name}",
        f"The moment {f1_name} vs {f2_name} became a horror movie",
        f"Ghost HP energy. {f1_name} vs {f2_name} defies all logic",
        f"The last gasp win that nobody predicted in AlgoRot",
        f"They were invisible on the HP bar and STILL pulled through",
        f"Nothing should have saved them. Something did",
        f"A survival story that belongs in the AlgoRot Hall of Fame",
        f"The fight that proves one HP is enough",
        f"How is this even possible? {f1_name} vs {f2_name} shocks everyone",
        f"A victory so improbable the simulation almost broke",
        f"They played dead and then absolutely did not die",
        f"The HP bar said no chance. The fighter said watch me",
        f"One pixel of health and all the heart in the world",
        f"The math did not add up. They won anyway. {f1_name} vs {f2_name}",
        f"This AlgoRot match gave me actual anxiety",
        f"The most nail-biting finish in {f1_name} vs {f2_name} yet",
        f"When survival instinct overrides everything else in AlgoRot",
        f"The fighter that physics forgot to kill in {f1_name} vs {f2_name}",
        f"Running on pure chaos and zero HP in {f1_name} vs {f2_name}",
        f"The most cinematic last stand in AlgoRot history",
        f"They literally should not have made it out of this one",
        f"Snatching victory from the jaws of total destruction",
        f"The final second save that rewrote the whole story",
        f"This HP was basically decorative. They won anyway",
        f"A comeback so good it felt scripted in {f1_name} vs {f2_name}",
        f"This is what happens when you refuse to tap out",
        f"The AlgoRot fighter with absolutely zero chill about losing",
        f"Surviving on fumes and somehow winning in {f1_name} vs {f2_name}",
        f"One hit away from defeat and they found two hits of their own",
        f"The moment {f1_name} vs {f2_name} turned into a comeback story",
        f"Running on luck fumes and nothing else in this AlgoRot match",
        f"The win that rewired my brain a little bit",
        f"Technically dead but emotionally very much alive",
        f"How many times can one fighter cheat death? AlgoRot answers",
        f"The HP bar was a lie and {f1_name} vs {f2_name} proved it",
        f"Refusing to go down no matter what in {f1_name} vs {f2_name}",
        f"The last breath win that belongs in AlgoRot lore",
        f"Nobody picks the underdog. The underdog does not care",
        f"Surviving when the odds said absolutely not in AlgoRot",
        f"An HP that small should be a death sentence. It was not",
        f"The comeback arc in {f1_name} vs {f2_name} is genuinely unreal",
        f"Who programmed this fighter to never give up?",
        f"Against all probability this is what happened in {f1_name} vs {f2_name}",
        f"The most heart-racing AlgoRot finish of the season",
        f"A win built entirely out of stubbornness and physics",
        f"The ghost health bar victory in {f1_name} vs {f2_name}",
        f"One last swing and somehow it landed in AlgoRot",
        f"The entire vibe of this fight changed in the last second",
        f"Clinging to life and winning anyway in {f1_name} vs {f2_name}",
        f"The simulation said it was over. The fighter disagreed",
        f"You physically cannot predict the ending of {f1_name} vs {f2_name}",
        f"The luckiest alive fighter in all of AlgoRot",
        f"This match had ZERO business going the way it did",
        f"From deletion territory to outright winning in {f1_name} vs {f2_name}",
        f"The most emotionally devastating comeback in AlgoRot",
        f"AlgoRot does it again. You will not see this ending coming",
        f"Barely a health bar left but all the fight in the world",
        f"The comeback that nobody in AlgoRot history can top",
        f"Surviving by a miracle and capitalizing on it in {f1_name} vs {f2_name}",
        f"Technically on borrowed time. Absolutely did not show it",
        f"The most insane survival in AlgoRot this year",
        f"They had nothing left. They still had enough",
        f"The ending of {f1_name} vs {f2_name} will haunt me",
        f"Fighting on fumes against a full tank in AlgoRot",
        f"The 1 HP win that set the AlgoRot community on fire",
        f"This should have ended five hits earlier. It did not",
        f"AlgoRot physics just handed someone the most dramatic win ever",
        f"Living on the edge and THRIVING in {f1_name} vs {f2_name}",
        f"Nobody expected this ending in {f1_name} vs {f2_name}. Nobody",
        f"The last laugh goes to the fighter everyone counted out",
        f"A comeback so improbable the simulation flagged it as an error",
    ]

    blowout = [
        f"ABSOLUTE DOMINATION in {f1_name} vs {f2_name}",
        f"Is one of these fighters broken in AlgoRot?",
        f"FLAWLESS VICTORY. Someone gets absolutely destroyed",
        f"Nobody can stop them. Just watch",
        f"They did not stand a chance",
        f"The most one-sided battle in AlgoRot history",
        f"Pure Destruction in {f1_name} vs {f2_name}",
        f"Someone just proved they are the final boss of AlgoRot",
        f"A masterclass in physics and total domination",
        f"Someone got absolutely vaporized in {f1_name} vs {f2_name}",
        f"Speedrun energy. Finished with ZERO MERCY",
        f"Are they cheating? (Flawless Win in {f1_name} vs {f2_name})",
        f"Casually wiping the floor with their opponent in AlgoRot",
        f"Total annihilation. Zero damage taken",
        f"They need to be deleted after what just happened in AlgoRot",
        f"This was not a fight. This was an execution",
        f"The most lopsided physics battle AlgoRot has ever produced",
        f"One fighter showed up. The other just got erased",
        f"Is this even fair? {f1_name} vs {f2_name} is brutal",
        f"Maximum efficiency. Minimum mercy in AlgoRot",
        f"They took zero damage and gave everything in {f1_name} vs {f2_name}",
        f"A complete shutdown performance in AlgoRot",
        f"This was a demolition dressed up as a battle",
        f"The most dominant AlgoRot win I have ever seen",
        f"Did someone forget to give the other fighter a weapon?",
        f"A performance so clean it feels illegal in {f1_name} vs {f2_name}",
        f"From start to finish there was only one fighter here",
        f"The simulation had no answer for this level of dominance",
        f"This AlgoRot run is what peak performance looks like",
        f"Untouchable. Unstoppable. Unreal performance in {f1_name} vs {f2_name}",
        f"The most complete destruction in AlgoRot history",
        f"They treated this fight like a warmup",
        f"Not a single scratch. Just pure AlgoRot supremacy",
        f"The opponent barely existed in this one",
        f"Absolute unit energy in {f1_name} vs {f2_name}",
        f"This was not competitive. This was a showcase",
        f"Zero HP taken. Zero hesitation. Total victory in AlgoRot",
        f"The kind of win that makes you wonder if the code is rigged",
        f"A physics-powered freight train with no brakes in {f1_name} vs {f2_name}",
        f"They did not just win. They sent a message in AlgoRot",
        f"The most effortless flawless run in {f1_name} vs {f2_name}",
        f"Watching this domination felt genuinely unfair",
        f"If AlgoRot had a final boss it would look exactly like this",
        f"The other fighter showed up but was never really in it",
        f"Peak AlgoRot performance and it was not even close",
        f"Absolute zero competition in {f1_name} vs {f2_name}",
        f"They dismantled the opponent piece by piece in AlgoRot",
        f"This fighter did not leave anything on the table",
        f"The cleanest win in recent AlgoRot memory",
        f"No drama needed when you are this dominant",
        f"A shutout performance for the AlgoRot record books",
        f"The most one-way traffic in the history of {f1_name} vs {f2_name}",
        f"They made it look painfully easy in AlgoRot",
        f"Is this physics or is this art? {f1_name} vs {f2_name}",
        f"Full health at the end. Did not even break a sweat",
        f"The opponent had no answer at any point in {f1_name} vs {f2_name}",
        f"The algorithm cooked something truly terrifying today in AlgoRot",
        f"Dominant from the very first collision in {f1_name} vs {f2_name}",
        f"This win was so clean it barely made a sound",
        f"An absolutely clinical performance in {f1_name} vs {f2_name}",
        f"The gap between these two fighters is honestly shocking",
        f"Never in danger. Always in control in {f1_name} vs {f2_name}",
        f"The most convincing win the AlgoRot simulation has ever generated",
        f"Completely outclassed in every single dimension in AlgoRot",
        f"This fighter did not take damage. They gave a lesson",
        f"The performance of a lifetime by AlgoRot standards",
        f"Imagine getting this destroyed with full health still showing",
        f"A total obliteration that the simulation is still processing",
        f"Nobody who watched this doubted who was going to win",
        f"The other fighter was more of a prop than a participant",
        f"Surgical precision and zero sympathy in {f1_name} vs {f2_name}",
        f"They ran through the opponent like they were not even there",
        f"A performance so dominant it almost feels scripted in AlgoRot",
        f"The most terrifying thing in AlgoRot is this flawless run",
        f"You can tell from the very first second who is winning this",
        f"A FLAWLESS W that needs to be studied in {f1_name} vs {f2_name}",
        f"Why does this keep happening in AlgoRot? Completely one-sided",
        f"This fighter was always going to win and the algorithm knew it",
        f"One fighter brought everything. The other brought nothing",
        f"They took the game personally and the opponent paid for it",
        f"The most embarrassing HP differential in {f1_name} vs {f2_name} history",
        f"A win so large it barely fits on the HP bar",
        f"Completely sealed from the opening collision in AlgoRot",
        f"The other fighter was simply outmatched from the start",
        f"They ran the algorithm better than the algorithm expected",
        f"Total health remaining after a FLAWLESS annihilation in AlgoRot",
        f"The physics engine bowed down during this {f1_name} vs {f2_name} run",
        f"Poured everything out and never took a drop back in AlgoRot",
        f"What a thing to witness. Pure AlgoRot supremacy",
        f"The kind of performance that makes other fighters delete themselves",
        f"Historically dominant. This AlgoRot match is required viewing",
        f"Zero contest. Zero drama. All dominance in {f1_name} vs {f2_name}",
        f"This fighter ran the table and never looked back in AlgoRot",
        f"The perfect AlgoRot run that might never be repeated",
        f"This is what happens when the algorithm absolutely cooks",
        f"A W so clean the simulation had to double check it was real",
        f"They absorbed nothing and delivered everything in {f1_name} vs {f2_name}",
        f"The most dominant AlgoRot fighter we have seen all season",
        f"No sweat. No damage. Just results in {f1_name} vs {f2_name}",
        f"A flawless performance that the AlgoRot archive will never forget",
        f"The algorithm decided one fighter was simply better today",
        f"One-sided does not even begin to cover it in {f1_name} vs {f2_name}",
        f"The HP gap at the end tells the whole story in AlgoRot",
        f"A thorough beating from the very first moment in AlgoRot",
        f"This result was never in doubt for a single frame",
        f"The winner cruised and the loser suffered in {f1_name} vs {f2_name}",
        f"Not a close fight. Not even slightly in {f1_name} vs {f2_name}",
        f"The cleanest route to victory AlgoRot has ever charted",
        f"An HP lead that only ever grew in this AlgoRot match",
        f"The gap opened early and it never closed in {f1_name} vs {f2_name}",
        f"One fighter handled this. The other got handled in AlgoRot",
        f"A result written in the first five seconds in AlgoRot",
        f"The domination was quiet. The result was loud in {f1_name} vs {f2_name}",
        f"They outpaced the damage intake from start to finish in AlgoRot",
        f"A comprehensive win in {f1_name} vs {f2_name} that left nothing open",
        f"The algorithm handed one side a complete gift today in AlgoRot",
        f"A slow and methodical destruction in {f1_name} vs {f2_name}",
        f"This level of control does not happen often in AlgoRot",
        f"A performance that made the fight feel like practice in {f1_name} vs {f2_name}",
        f"The margin grew every second in this AlgoRot battle",
        f"They absorbed the fight and gave back double in AlgoRot",
        f"From the jump this was never going to be close in {f1_name} vs {f2_name}",
        f"A smooth and total takeover in {f1_name} vs {f2_name}",
        f"The difference in class was obvious from frame one in AlgoRot",
        f"They were never threatened and that says everything in {f1_name} vs {f2_name}",
        f"The kind of AlgoRot win where you already know the ending",
        f"One side came to fight. The other came to finish in AlgoRot",
        f"The HP bars could not have been more different in {f1_name} vs {f2_name}",
        f"A controlled demolition from start to finish in AlgoRot",
        f"The opposition had chances. They could not convert any of them",
        f"Winning with that much HP left is rare in AlgoRot. This was rare",
        f"An opponent that just could not close the gap in {f1_name} vs {f2_name}",
        f"They dictated the entire fight and the result shows it",
        f"Not every AlgoRot fight is close. This one was the proof",
        f"The dominant fighter here set the tempo and never lost it",
        f"A convincing win that came with plenty of HP to spare",
        f"The fight was decided before the last hit in AlgoRot",
        f"No fightback. No hope. Just a dominant run in {f1_name} vs {f2_name}",
        f"A performance that the loser will be haunted by in AlgoRot",
        f"One of the more comfortable AlgoRot wins you will ever see",
        f"This fighter smelled blood early and never let go in AlgoRot",
        f"A win that was never truly in question in {f1_name} vs {f2_name}",
        f"The most comfortable margin in recent AlgoRot history",
        f"They were simply on another level in {f1_name} vs {f2_name}",
        f"A fight where one side never showed up in AlgoRot",
        f"The damage ratio in this AlgoRot match is genuinely alarming",
        f"Controlled. Clinical. Completely dominant in {f1_name} vs {f2_name}",
        f"The AlgoRot engine handed someone a masterclass today",
        f"A blowout so clean it almost looked polite in {f1_name} vs {f2_name}",
        f"A margin this wide is its own kind of statement in AlgoRot",
    ]

    standard = [
        f"{f1_name} vs {f2_name} ends in SHOCKING Sudden Death",
        f"The physics in this {f1_name} vs {f2_name} match went CRAZY",
        f"10 Parries Later. {f1_name} vs {f2_name} goes Nuclear",
        f"This {f1_name} vs {f2_name} Sudden Death will give you chills",
        f"NO WAY. The {f1_name} vs {f2_name} Match Was Too Close",
        f"Wait until the end of this {f1_name} vs {f2_name} fight",
        f"You will not believe how {f1_name} vs {f2_name} ends",
        f"Are we dreaming? {f1_name} vs {f2_name} goes off the rails",
        f"This collision between {f1_name} and {f2_name} broke the engine",
        f"The most intense rivalry yet in {f1_name} vs {f2_name}",
        f"Pure satisfying chaos in {f1_name} vs {f2_name} Sudden Death",
        f"My brain melted watching {f1_name} vs {f2_name}",
        f"Who are you rooting for? {f1_name} vs {f2_name} Epic Ending",
        f"Gravity stopped working in this {f1_name} vs {f2_name} clash",
        f"The exact moment {f1_name} vs {f2_name} turned into a movie",
        f"This match had absolutely no right to be this entertaining",
        f"The most unpredictable AlgoRot battle of the week",
        f"Neither side could pull away in this wild {f1_name} vs {f2_name} brawl",
        f"The turning point in {f1_name} vs {f2_name} will blow your mind",
        f"A fight so chaotic the simulation had to catch its breath",
        f"Every swing mattered in this insane {f1_name} vs {f2_name} matchup",
        f"AlgoRot served up something special with {f1_name} vs {f2_name}",
        f"The most evenly matched AlgoRot battle in recent memory",
        f"Back and forth chaos all the way to the final blow",
        f"The AlgoRot algorithm absolutely went unhinged in {f1_name} vs {f2_name}",
        f"Two equals going to war. Only one survives in AlgoRot",
        f"This fight had no business being this good",
        f"Completely unpredictable from first hit to last in {f1_name} vs {f2_name}",
        f"The most watched AlgoRot rematch about to happen after this",
        f"The physics engine went full drama mode in {f1_name} vs {f2_name}",
        f"An absolute banger of a match from start to finish",
        f"The moment {f1_name} vs {f2_name} became legendary in AlgoRot",
        f"AlgoRot just generated something that cannot be unseen",
        f"Close. Intense. Chaotic. {f1_name} vs {f2_name} had everything",
        f"The match that made me forget to breathe in {f1_name} vs {f2_name}",
        f"The simulation decided to go full cinematic in this one",
        f"Not a single dull moment in this {f1_name} vs {f2_name} battle",
        f"The most satisfying ending AlgoRot has produced this week",
        f"Nobody could predict this result in {f1_name} vs {f2_name}",
        f"When the algorithm decides to get dramatic in AlgoRot",
        f"A razor-thin margin decided this wild {f1_name} vs {f2_name} fight",
        f"The cleanest AlgoRot chaotic brawl you will see today",
        f"This kind of finish is exactly why AlgoRot has fans",
        f"AlgoRot physics went completely sideways in {f1_name} vs {f2_name}",
        f"Two fighters. One winner. Zero predictability in AlgoRot",
        f"The most dramatic HP race in {f1_name} vs {f2_name} history",
        f"An AlgoRot battle that kept swinging right until the end",
        f"The collision that changed everything in {f1_name} vs {f2_name}",
        f"This is what peak algorithmic combat looks like",
        f"Fighting until nothing is left in {f1_name} vs {f2_name}",
        f"Absolutely zero chill from either fighter in this AlgoRot match",
        f"The most watched fight on the channel is about to be this one",
        f"Total warfare from the first frame in {f1_name} vs {f2_name}",
        f"An AlgoRot matchup that deserves to be studied",
        f"Both fighters showed up prepared to destroy in {f1_name} vs {f2_name}",
        f"The match that defined the entire {f1_name} vs {f2_name} rivalry",
        f"AlgoRot finally gave us the {f1_name} vs {f2_name} match we deserved",
        f"The fight that got away from both sides in AlgoRot",
        f"When the damage numbers get big things get real fast in AlgoRot",
        f"The greatest battle in the {f1_name} vs {f2_name} series so far",
        f"This AlgoRot fight has more plot twists than a short film",
        f"Completely even right up until the moment it was not",
        f"The final exchange in {f1_name} vs {f2_name} is everything",
        f"Mayhem physics and a ridiculous ending in {f1_name} vs {f2_name}",
        f"This is exactly why I watch AlgoRot every single day",
        f"Two unstoppable forces. One unforgettable result in AlgoRot",
        f"The battle that shook the AlgoRot leaderboard in {f1_name} vs {f2_name}",
        f"Sheer aggression from both sides right until the final frame",
        f"Tied on chaos. Decided by physics in {f1_name} vs {f2_name}",
        f"The match that AlgoRot was literally built to generate",
        f"A rivalry match so good it needs a sequel in AlgoRot",
        f"When the HP bars get this close the crowd loses it",
        f"This fight aged five years in thirty seconds in AlgoRot",
        f"The intensity of {f1_name} vs {f2_name} is almost too much",
        f"If you only watch one AlgoRot fight today make it this one",
        f"This outcome in {f1_name} vs {f2_name} made absolutely no sense and yet",
        f"The simulation generated something extraordinary in this match",
        f"When two fighters are this close sparks literally fly in AlgoRot",
        f"The most evenly balanced AlgoRot fight of the entire season",
        f"Neither side blinked in this {f1_name} vs {f2_name} showdown",
        f"The moment this AlgoRot match stopped being normal",
        f"A genuine classic in the making from {f1_name} vs {f2_name}",
        f"When AlgoRot says no mercy it absolutely means it",
        f"This battle had energy from the very first frame in AlgoRot",
        f"The ending of {f1_name} vs {f2_name} will be talked about for days",
        f"AlgoRot has never generated a closer fight than this one",
        f"The most chaotically balanced battle in the entire series",
        f"A fight where every single decision mattered in {f1_name} vs {f2_name}",
        f"Neither fighter wanted to be the one who lost this one",
        f"The algorithm completely lost the plot in {f1_name} vs {f2_name}",
        f"Head-to-head and completely unpredictable in AlgoRot",
        f"The most dramatic trading sequence in {f1_name} vs {f2_name} history",
        f"This AlgoRot match ended in a way nobody in the comments predicted",
        f"A genuinely wild ride from first hit to last breath in AlgoRot",
        f"AlgoRot peaked today and it peaked during {f1_name} vs {f2_name}",
        f"The simulation generated drama and then kept going in AlgoRot",
        f"Equal damage. Unequal endings. The beauty of {f1_name} vs {f2_name}",
        f"The most competitive fight the algorithm has ever produced",
        f"Both fighters threw everything and only one thing remained in AlgoRot",
        f"The AlgoRot simulation just delivered its most chaotic finish yet",
        f"The fight swung so many times it made my head spin in AlgoRot",
        f"A result that could have gone either way right up to the end",
        f"They traded everything and only one walked away in {f1_name} vs {f2_name}",
        f"The most edge-of-your-seat HP race in {f1_name} vs {f2_name}",
        f"This AlgoRot fight went exactly as chaotic as the best ones do",
        f"One wrong move and this entire result changes in {f1_name} vs {f2_name}",
        f"The kind of fight where momentum flipped every few seconds in AlgoRot",
        f"No runaway winner. Just a brutal back-and-forth in {f1_name} vs {f2_name}",
        f"This is the fight type that makes AlgoRot worth watching",
        f"A messy competitive brawl with a clean winner in {f1_name} vs {f2_name}",
        f"Neither fighter could get comfortable in this one in AlgoRot",
        f"The most convincingly competitive {f1_name} vs {f2_name} fight yet",
        f"Both HP bars moved constantly. Only one hit zero first",
        f"A grind of a fight that paid off in the most satisfying way",
        f"The fight felt even. The ending said otherwise in {f1_name} vs {f2_name}",
        f"Both fighters gave it everything in this AlgoRot match",
        f"An AlgoRot fight that earns the rewatch at the end",
        f"Nobody was safe in this {f1_name} vs {f2_name} battle",
        f"The most competitive damage exchange in recent AlgoRot history",
        f"Two fighters refusing to yield in {f1_name} vs {f2_name}",
        f"A genuine war that finally found a winner in AlgoRot",
        f"The fight never settled. Neither did my heartbeat in {f1_name} vs {f2_name}",
        f"A hard-fought result in {f1_name} vs {f2_name} that could easily be reversed",
        f"The closest-feeling fight with this HP gap in AlgoRot",
        f"They pushed each other to the absolute edge in {f1_name} vs {f2_name}",
        f"Every hit felt meaningful in this AlgoRot battle",
        f"An AlgoRot match that rewards you for watching every second",
        f"The fight looked even until suddenly it was not in {f1_name} vs {f2_name}",
        f"This is what a proper AlgoRot battle looks like",
        f"A fight that neither side dominated and only one side won",
        f"The tension in this {f1_name} vs {f2_name} match never fully broke",
        f"A winner emerged but both fighters earned their moment in AlgoRot",
        f"The most satisfying mid-range finish in {f1_name} vs {f2_name}",
        f"No one was pulling away and then suddenly someone was in AlgoRot",
        f"An AlgoRot battle with genuine momentum shifts throughout",
        f"Both fighters came to win and only physics could separate them",
        f"A fight with real drama hidden in the middle of it in AlgoRot",
        f"The HP stayed close for so long the ending hit different in {f1_name} vs {f2_name}",
        f"Two fighters. Equal hunger. One algorithm. AlgoRot decides",
        f"The winner here had to actually earn it in {f1_name} vs {f2_name}",
        f"This AlgoRot fight was never going to be easy and it was not",
        f"A competitive result that the winner had to fight hard for",
        f"The simulation built something genuinely entertaining in {f1_name} vs {f2_name}",
        f"An AlgoRot fight that made both outcomes feel possible",
        f"The most evenly contested {f1_name} vs {f2_name} in the series",
        f"A fight decided by the smallest edge in the biggest moment",
        f"When both fighters are this committed something has to give in AlgoRot",
        f"The HP gap told a story. The fight told a better one in {f1_name} vs {f2_name}",
        f"AlgoRot came through with a proper competitive fight today",
        f"The kind of AlgoRot match that makes you want to run it back immediately",
    ]

    stomp = [
        f"An absolutely untouchable performance in {f1_name} vs {f2_name}",
        f"They finished with over half their HP. This was never close",
        f"A surgical dismantling in {f1_name} vs {f2_name}",
        f"This is what a perfect AlgoRot run looks like",
        f"The opponent never even dented them in {f1_name} vs {f2_name}",
        f"Running at near-full health through an entire fight in AlgoRot",
        f"The most dominant margin of victory in AlgoRot this season",
        f"They barely took any damage in {f1_name} vs {f2_name}",
        f"An efficiency rating this high should be illegal in AlgoRot",
        f"The cleanest win condition the algorithm has ever produced",
        f"Zero drama. Maximum destruction in {f1_name} vs {f2_name}",
        f"Like they were not even fighting the same battle in AlgoRot",
        f"The opponent landed nothing of consequence in {f1_name} vs {f2_name}",
        f"A walking health bar making a statement in AlgoRot",
        f"The most one-sided HP gap in {f1_name} vs {f2_name} history",
        f"Walked in fresh. Walked out fresher. AlgoRot perfection",
        f"Nearly untouched from start to finish in {f1_name} vs {f2_name}",
        f"The cleanest margin this AlgoRot simulation has ever generated",
        f"This performance was not a fight. It was a demonstration",
        f"AlgoRot produced the most efficient fighter on record in {f1_name} vs {f2_name}",
        f"The most pristine health bar after a win in AlgoRot",
        f"They finished the fight almost completely undamaged",
        f"A 60 plus percent HP finish. Someone just got embarrassed in AlgoRot",
        f"The opponent hit them once and that was the highlight in {f1_name} vs {f2_name}",
        f"An AlgoRot run this clean has never been seen before",
        f"Entered at full health. Left at almost full health. Won anyway",
        f"The most dominant performance without breaking a sweat in AlgoRot",
        f"A victory lap disguised as a fight in {f1_name} vs {f2_name}",
        f"The HP bar barely moved on one side in this AlgoRot match",
        f"Completely untouchable from the opening frame in AlgoRot",
        f"The most lopsided HP remaining gap in {f1_name} vs {f2_name}",
        f"They looked like a tutorial boss fighting a beginner in AlgoRot",
        f"Not a scratch. Not a care. A dominant win in AlgoRot",
        f"The physics could not touch them in {f1_name} vs {f2_name}",
        f"This is what maximum efficiency looks like in AlgoRot",
        f"A performance so clinical it felt calculated by design",
        f"The highest HP finish AlgoRot has recorded this season in {f1_name} vs {f2_name}",
        f"This was never a fight. It was always an execution",
        f"The most lopsided finish in {f1_name} vs {f2_name} to date",
        f"The algorithm made one fighter look like a god today",
        f"Barely breathed heavily through the entire fight in AlgoRot",
        f"A near-perfect run in {f1_name} vs {f2_name} that redefines dominance",
        f"The opponent had no answer for this fighter at all in AlgoRot",
        f"The definition of effortless in {f1_name} vs {f2_name}",
        f"An HP bar so full after the fight it seemed wrong in AlgoRot",
        f"Dealt everything. Absorbed nothing. Perfection in {f1_name} vs {f2_name}",
        f"The most impenetrable fighter the algorithm has ever generated",
        f"Not just a win. A statement. AlgoRot crowns a new standard",
        f"This fighter took almost zero punishment in {f1_name} vs {f2_name}",
        f"A dominant performance that sets a new AlgoRot benchmark",
        f"The cleanest HP gap between winner and loser in AlgoRot history",
        f"An opponent who never figured out how to land a hit in {f1_name} vs {f2_name}",
        f"Walking into a fight invincible and walking out proving it in AlgoRot",
        f"The most comfortable win the algorithm has ever simulated",
        f"They could have fought two of them and still looked like this",
        f"A high HP finish so rare AlgoRot had to double check it",
        f"The most complete performance in {f1_name} vs {f2_name} history",
        f"An untouchable result that no simulation should be able to produce",
        f"They were not competing. They were showcasing in AlgoRot",
        f"The kind of finish that makes the other fighter question everything in {f1_name} vs {f2_name}",
        f"The best HP conservation in AlgoRot match history",
        f"An AlgoRot fighter operating at maximum capacity",
        f"Left the fight healthier than most fighters enter in {f1_name} vs {f2_name}",
        f"The algorithm designed a perfect fighter for this round in AlgoRot",
        f"Absorbing almost nothing while delivering total destruction",
        f"A high HP victory that proves not all weapons are equal in AlgoRot",
        f"The most effortless AlgoRot win of the entire season",
        f"This fighter exists in a different tier from everyone else in AlgoRot",
        f"The cleanest technical performance AlgoRot has generated yet",
        f"Maximum output. Minimum input. The AlgoRot formula perfected",
        f"A lopsided HP finish that speaks for itself in {f1_name} vs {f2_name}",
        f"The opponent existed. They did not matter. AlgoRot is brutal",
        f"They barely needed the full duration to prove a point in AlgoRot",
        f"A near-flawless health record after a full fight in {f1_name} vs {f2_name}",
        f"The most intact health bar after battle in AlgoRot this year",
        f"They showed up and did not let anything touch them in {f1_name} vs {f2_name}",
        f"The damage output was overwhelming. The damage received was nothing",
        f"AlgoRot just generated the most dominant champion yet",
        f"A performance that makes the leaderboard look unfair in {f1_name} vs {f2_name}",
        f"Controlled the entire fight without ever being in danger in AlgoRot",
        f"The most one-sided HP differential in this AlgoRot matchup series",
        f"A fighter running at peak efficiency in {f1_name} vs {f2_name}",
        f"So dominant the fight felt like a setup in AlgoRot",
        f"The kind of win that resets everyone's expectations in AlgoRot",
        f"A machine-like performance in {f1_name} vs {f2_name}",
        f"The best efficiency rating in AlgoRot this entire season",
        f"Not just winning. Winning without consequence in {f1_name} vs {f2_name}",
        f"The most overpowered round result in AlgoRot to date",
        f"They made the simulation look like a practice run in {f1_name} vs {f2_name}",
        f"An untouchable margin that the AlgoRot archive will remember",
        f"The benchmark run that all future AlgoRot fighters will be compared to",
        f"A fight so one-sided physics barely got involved in {f1_name} vs {f2_name}",
        f"The cleanest clean sweep in {f1_name} vs {f2_name} history",
        f"Running on full power from start to finish in AlgoRot",
        f"Practically glowing with health after the fight in {f1_name} vs {f2_name}",
        f"The fighter that turned an AlgoRot match into a training session",
        f"A supremacy run so clean it almost felt wrong to watch",
        f"The highest HP differential the AlgoRot engine has ever produced",
        f"Total control from start to finish in {f1_name} vs {f2_name}",
        f"The algorithm created a monster today in {f1_name} vs {f2_name}",
    ]

    return {
        "ghost": ghost,
        "clutch": clutch,
        "standard": standard,
        "blowout": blowout,
        "stomp": stomp,
    }